### ISSUE TITLE
Conflicting types in RefitStubs.cs

### ISSUE THREAD

**Issue by mteper** [paulcbetts/refit#101]
I have two different sets of REST API in my project, both enabled by Refit. Both API reference a type named Project, but these are separate and unrelated Project classes that live in different namespaces. Unfortunately, when Refit puts stubs for both API into the same file, with one set of usings, I get a naming conflict.

One way to resolve this (short of me renaming my classes, which may not always be possible) is to have the InterfaceStubGenerator.cs generate fully qualified type names rather than reuse the names it finds in the interface file. To do that, the Roslyn syntax model needs to be converted to a semantic model and queried.

Possibly useful reading:
http://stackoverflow.com/a/9336238/56499
http://blogs.msdn.com/b/csharpfaq/archive/2011/11/23/using-the-roslyn-symbol-api.aspx

**Comment by flagbug** [comment]
RefitStubs.cs doesn't exist anymore, so this should be fixed
