### ISSUE TITLE
Can't send a POST request without Body

### ISSUE THREAD

**Issue by avanpo** [paulcbetts/refit#112]
There's an issue where a lack of post body does not receive the proper content type header. I've set the the header Content-Type: application/x-www-form-urlencoded; charset=UTF-8, but when I send a post request containing only headers the server complains about a bad request content type, expecting application/x-www-form-urlencoded.

I can get around this by including a [Body(BodySerializationMethod.UrlEncoded)] with an empty dictionary, for example. However, I don't think this should be necessary.

**Comment by bennor** [comment]
@onovotny What do you think is the best approach here? Just add an empty `FormUrlEncodedContent` body to any post request with no body? Or empty `StringContent` if there are headers present which have to be set on `HttpContent`?

The latter seems less likely to be a breaking change.

**Comment by onovotny** [comment]
I think an empty string content? what does the full raw payload look like then?

**Comment by bennor** [comment]
Looks busted. Seems that `StringContent` forces the addition of a `Content-Type` header, so when you add another one manually you get two.

However, it appears that adding an empty `ByteArrayContent` works a little better. Does nothing by default other than adding a `Content-Length: 0` header, so I think we can probably safely do this in all cases when there isn't a body parameter provided. Then people can manually set their content type with a `[Headers()]` (or `[Header]`) attribute, if they need to.

**Comment by onovotny** [comment]
I wonder how common a POST is without a body anyway.

**Comment by onovotny** [comment]
but a Content-Length of 0 seems legit even in that case.

**Comment by bennor** [comment]
Original problem was that a specific header was required (`Content-Type`), but you can't add that header to an `HttpRequestMessage` unless it has a non-null `Content`. PR incoming.

**Comment by bennor** [comment]
This won't work for GET or HEAD requests because `HttpClient` doesn't allow it (it throws an exception in `HttpWebRequest.CheckProtocol()`), but the linked PR adds support for POST, PUT, etc.
