### ISSUE TITLE
RefitStubs and vcs

### ISSUE THREAD

**Issue by omares** [paulcbetts/refit#113]
Should we commit the generated refitsubs into the vcs, or do the get generated every time?

**Comment by paulcbetts** [comment]
@omares I would .gitignore them, but either one works - you should only see file changes if your interface code changes so it shouldn't get in the way that much

**Comment by balauru** [comment]
If we .gitignore in some cases the `InterfaceStubGenerator` will throw a FileNotFoundException, it happend to me after updating to a new version on the CI
