### ISSUE TITLE
"SetUp : System.NotImplementedException : You've somehow included the PCL version of Refit in your app. You need to use the platform-specific version!"

### ISSUE THREAD

**Issue by omares** [paulcbetts/refit#114]
I created a PCL compatible library and added refit via nuget. Whats going on? :) There isnt even a platform specific version of refit.

**Comment by paulcbetts** [comment]
There *is* a platform-specific version of Refit. How are you running the code? Via a unit test? An App?

**Comment by omares** [comment]
Ugh, sorry about the lack of information. Trying to debug the problem since a few hours made me loose my focus.

I am using xamarin studio with an unit test project. So yes, i am running the code via an unit test using nunit. 

But it seems my solution is broken, creating a new solution with an unit test project, adding refit via nuget and copy pasting the code works perfectly fine. :(

**Comment by paulcbetts** [comment]
@omares If you want to fix it by-hand, delete the assembly reference in your unit test project to Refit, then point it to the .NET 4.5 one

**Comment by omares** [comment]
That seemd to fix the PCL issues, thanks.

Now i get `SetUp : System.IO.FileNotFoundException : Could not load file or assembly or one of its dependencies.` it has something todo with the main project the test-project is referencing but i cant find it.

**Comment by omares** [comment]
Closing this now, it has to do something with xamarin studio. Executing the tests in visual studio 2013 works perfectly fine.

**Comment by decriptor** [comment]
Since this is still an issue I'm going to reopen this.

**Comment by paulcbetts** [comment]
@decriptor Are you trying to use Refit with 32-bit Xamarin.iOS?

**Comment by paulyoung** [comment]
@omares did you ever find a solution to the `System.IO.FileNotFoundException` issue?

I'm experiencing the same thing. Tests run fine in Visual Studio.

**Comment by omares** [comment]
@paulyoung afaik the issue was somehow related to the fact that using visual studio and xamarin studio in parallel broke the project file. i recreated our affected test project form ground up in xamarin studio and it worked. But as we abandoned refit in favor of another library i did not care much to investigate further.

**Comment by devkhan** [comment]
Can anyone please point me to platform specific versions of Refit, I can't find them. There's only a single package in nuget also.

Also, as I am developing a PCL for multiple platforms, do I need to add the corresponding Refit packages?

**Comment by Cheesebaron** [comment]
You are right there is only one NuGet, but it contains the DLL's for each of the supported platforms.

**Comment by devkhan** [comment]
Found it. Thanks @Cheesebaron. Can you also answer the other part of my question?

**Comment by Cheesebaron** [comment]
Afaik I only added it to my PCL. That should be enough. You will find out at runtime though.

**Comment by ahmedalejo** [comment]
@devkhan  @Cheesebaron that ain´t enough, you´ll have to install the same nuget package into all your platform specific projects as well the one installed in the PCL is just a stub;

Check this posts for more detail [The Bait and Switch PCL Trick](http://log.paulbetts.org/the-bait-and-switch-pcl-trick/) by @paulcbetts

**Comment by Robert-Altland** [comment]
I am unable to successfully execute tests that depend on Refit when run in a Xamarin Studio .NET NUnit Library project. I have created a PCL 4.5 Profile78 project where I use Refit in the app. I have created a .NET NUnit Library Project that targets Mono/.NET 4.5. I have tried adding every version of the refit DLL to my test project and to the PCL, but nothing I have tried works. At best I get an error that I've somehow included the PCL version of Refit, and that I need to use a platform specific version. At worst I get a MissingMethodException for "RestService.For" across any tests that include Refit, whether or not refit related code actually runs in the test.

**Comment by golfqui** [comment]
On Visual Studio Community 7.0 (build 3146) for your platform specific app
1. Right click *Packages* directory and install refit
2. Right click *References* directory and select `Edit References...`
3. Under *.Net Assembly* tab click *Browse...* button
4. Select (from the project root) the proper library for your platform *packages/refit.../lib/\<Platform directory\>/Refit.dll*
5. Build and run without the error

**Comment by gebrehiywet** [comment]
install Refit in all platform projects. Android, iOS and Windows

**Comment by spurdow** [comment]
@golfqui please see #373
