### ISSUE TITLE
Sending duplicate header

### ISSUE THREAD

**Issue by pierskarsenbarg** [paulcbetts/refit#121]
I have two methods in my interface:

`[Get("/Session/GetId")]
        Task<ApiInt> GetProfileId([Header("X-SecureCode")] string secureCode, [Header("X-SessionId")] string sessionId);`

and 

`[Post("/Order")]
        Task<ApiOrder> CreateOrder([Body]ApiOrder order, [Header("X-SessionId")] string sessionId);`

that are called one after another (need the id to create the order).

However, I've noticed that when the second method is being run, the x-sessionid header is being sent over twice so when the API received it, it's coming as a comma separated list.

I've run this through fiddler and can see header coming over.

Is there something I should be doing in Refit to stop this happening?

**Comment by bennor** [comment]
Sounds like a bug - can you create a small repro project (or add a test)?

**Comment by bennor** [comment]
Also, totally unrelated but as of [2.2.0](https://github.com/paulcbetts/refit/releases/tag/2.2.0) you shouldn't need the `ApiInt` wrapper class anymore.

**Comment by pierskarsenbarg** [comment]
Ok, I've spent some time putting together something... (here: http://github.com/pierskarsenbarg/RefitTest)

However, (and annoyingly so) I can't reproduce the duplicated header.

It's not like it's coming through as two headers, the value is reproduced (so in my example, X-Header: foobar becomes X-Header: foobar, foobar

I had a look to see if there was anywhere that we were setting default headers and the only one is an accept header (setting it to application/json).

**Comment by RTodorov** [comment]
:+1: here. It only happens on my Android app. Exact same scenario, my session token header is being duplicated.

I'll dig into it and if I find anything relevant I'll update this post. I also have a couple of default headers (X-User-Agent, X-Locale) but it worked fine until... a couple of days ago! Suddenly it started duplicating the X-Token header!

**Comment by RTodorov** [comment]
Guys,

The problem is here:

            var s = value.ToString();
            request.Headers.TryAddWithoutValidation(name, s);

            if (request.Content != null) {
                request.Content.Headers.TryAddWithoutValidation(name, s);
            }

The header is being added twice only on POST calls, because request.Content is not null. Then, before the request is made, HttpClient joins the two headers into a single one, concatenated by a comma.

I don't know what triggered it since it started a couple of days ago. Before that, everything worked just fine, including POST requests.

The other question is: do we really need to add the header on both request.Headers and request.Content.Headers?

**Comment by RTodorov** [comment]
BTW, the above snippet is on RequestBuilderImplementation.cs, lines 154-159.

**Comment by RTodorov** [comment]
@bennor do you have any idea why this is happening? Apparently it doesn't affect everyone, for me it only happens on Android.

**Comment by bennor** [comment]
The reason we add to content headers as well is that some headers are [content headers](https://msdn.microsoft.com/en-us/library/system.net.http.headers.httpcontentheaders(v=vs.118).aspx) (and can't be added to the regular headers collection) and vice-versa.

My guess for what's happening here is that if the header isn't a known header (e.g. `X-Locale`), the framework doesn't know whether it's a content header or a regular header and will just add it to both collections.

I don't know of a clean way to check if a header is a known content header - there seems to be an internal static method in `HttpContentHeaders` (shown below), but I don't think we want to do get into calling that with reflection:

```csharp
    internal static void AddKnownHeaders(HashSet<string> headerSet)
    {
      headerSet.Add("Allow");
      headerSet.Add("Content-Disposition");
      headerSet.Add("Content-Encoding");
      headerSet.Add("Content-Language");
      headerSet.Add("Content-Length");
      headerSet.Add("Content-Location");
      headerSet.Add("Content-MD5");
      headerSet.Add("Content-Range");
      headerSet.Add("Content-Type");
      headerSet.Add("Expires");
      headerSet.Add("Last-Modified");
    }
```

That leaves us with:

* copying that into our own hashset and checking the header against it before adding to the headers collections; or
* checking for headers that match `@"(?i)X(-\w+)+"` and not adding them to the content headers.

Which do you reckon we should go for @paulcbetts? I'm thinking the first is probably going to be more reliable.

**Comment by cristianomad** [comment]
I'm facing the exact same problem. Please fix it.

**Comment by adrianolc** [comment]
I have that issue too

**Comment by rafaelfukuda** [comment]
Same here.

**Comment by julioww** [comment]
Same issue here.

**Comment by bennor** [comment]
Will fix this today or tomorrow.
