### ISSUE TITLE
Xamarin.Forms support

### ISSUE THREAD

**Issue by fonix232** [paulcbetts/refit#122]
I want to write an app using Refit, and also using Xamarin.Forms.

Adding Refit to all the projects works, mostly. The only exception is the iOS project - it fails to find System.Net.Http, but if I install it via NuGet (Microsoft.Net.Http), it cries about some System, System.Threading, etc. imports.

How can one add Refit to a Xamarin.Forms project?

**Comment by paulcbetts** [comment]
You need to use the 64-bit iOS (Unified) project, Refit isn't compatible with 32-bit iOS

**Comment by fonix232** [comment]
It is Unified project. Besides, both Android and the PCL gives the same error until I add the Microsoft.Net.Http NuGet package (which, if required, should be a dependency).

**Comment by RTodorov** [comment]
@fonix232 all you need to do is check the System.Net.Http on the references window, like this:

![screen shot 2015-01-26 at 3 42 01 pm](https://cloud.githubusercontent.com/assets/3506845/5904760/08469ef6-a572-11e4-8aea-8f72ff481c27.png)

Please note that you don't need to install Microsoft.Net.Http Nuget package. System.Net.Http is native on the Unified API. If you installed Microsoft.Net.Http, remove it and it should be fine.

**Comment by dcdroid** [comment]
Hi @fonix232 . Did Refit work for your Xamarin Forms project?

**Comment by fonix232** [comment]
Unfortunately it did not, though that project is on halt at the moment.
