### ISSUE TITLE
How to make Refit pass through proxy? (Charlie)

### ISSUE THREAD

**Issue by RTodorov** [paulcbetts/refit#123]
Refit is not using the proxy settings of iOS, so Charlie can't capture the Api calls.

Is there a way to make Refit use iOS proxy settings or can I programmatically specify which proxy to use?

**Comment by bennor** [comment]
You can in a preconfigured `HttpClient` when creating your Refit service:
```
var handler = new HttpClientHandler
{
    UseProxy = true,
    Proxy = new WebProxy("http://localhost:8888", false)
};
var client = new HttpClient(new HttpClientHandler())
{
	BaseAddress = new Uri("https://api.example.com/")
};
var foo = RestService.For<IFooApi>(client);
```

**Comment by paulcbetts** [comment]
If you control the app, a **much** better way to do this is simply to use http://runscope.com instead of dealing with proxy servers

**Comment by RTodorov** [comment]
@paulcbetts thanks, I'll try RunScope. Does it support .NET? I'm currently trying to use Crittercism but it just can't capture calls made with System.Net.Http.

**Comment by RTodorov** [comment]
@bennor thanks for your answer, it worked! Although I'm still trying to make Crittercism capture my calls.

**Comment by paulcbetts** [comment]
@RTodorov It's a server-side solution so it supports every language

**Comment by RTodorov** [comment]
Oh I see, Runscope work as a gateway. I really don't want my production calls to use a 3rd party gateway. I may use it for debug though.

Crittercism SDK on the other hand automatically captures every http call made with AFNetwork / NSUrlConnection on iOS and java.net.URLConnection on Android. But it doesn't capture System.Net.Http* on .NET.

**Comment by paulcbetts** [comment]
@RTodorov It's designed to do so actually, if you want to do that

> Crittercism SDK on the other hand automatically captures every http call made with AFNetwork / NSUrlConnection on iOS and java.net.URLConnection on Android.

Sounds like if you use [ModernHttpClient](https://github.com/paulcbetts/modernhttpclient) as your backing HttpMessageHandler, Crittercism will work then, no?

**Comment by RTodorov** [comment]
Yes, I'm trying it right now! Just bumped into your post about CFNetwork / NativeMessageHandler while searching for solutions.

It should definitely work but the app hangs when I make a call with Refit using my client:

var client = new HttpClient (new NativeMessageHandler ()) { BaseAddress = new Uri (APIUrl) };
var api = RestService.For<ICustomerApi> (client);

api.TestCall(); // hangs here!!

If I initialize Refit using this:

var api = RestService.For<ICustomerApi> (APIUrl);

it works fine (but doesn't use NativeMessageHandler).

Weird.... I'm still investigating but Refit doesn't print any errors..

**Comment by RTodorov** [comment]
Forget about it, ModernHttpClient solved my problem completely! I think there was an issue with RefitStubs not being regenerated. I cleaned the project, closed and reopened Xamarin and it worked!

That's awesome! Refit + ModernHttpClient + Crittercism working on both Android and iOS apps!

(Clearly Refit + ModernHttpClient is a great combination, once HttpClientHandler is much slower. Maybe you could mention it on Refit's README.md?)

**Comment by RTodorov** [comment]
May we close this issue? Refit + ModernHttpClient solves it.

**Comment by opcodewriter** [comment]
@bennor  FYI, about your statement:

> However, if the proxy is already set as your system proxy, it will be picked up by default

That doesn't work, unless I really create and set a  `HttpClientHandler` to `HttpClient`
