### ISSUE TITLE
Missing simple sample project

### ISSUE THREAD

**Issue by readiescards** [paulcbetts/refit#125]
Following recommendations of http://arteksoftware.com/resilient-network-services-with-xamarin 
I am trying refit.  

I added the refit package. Defined the interface but get build errors in RefitSubs.cs:
 'The type or namespace name 'Refit' could not be found...'

yet I've included using Refit; here and there.

Therefore do you have a simple working example?

**Comment by readiescards** [comment]
Creating a brand new simple Android App using Xamarin Studio 5.7 gives:

C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(3,3): Warning MSB3243: No way to resolve conflict between "Refit, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null" and "refit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null". Choosing "Refit, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null" arbitrarily. (MSB3243) (refit)

**Comment by paulcbetts** [comment]
@readiescards Are you using Xamarin.iOS 32-bit? This platform isn't supported

**Comment by readiescards** [comment]
XS on a PC windows 8
Thanks for reply

**Comment by paulcbetts** [comment]
I think you're misunderstanding me. When you open your "References" on your project, do you see a reference to "monotouch" or to "Xamarin.iOS"?

**Comment by readiescards** [comment]
Hi Paul

I'm trying with a basic PCL based Android app - so references just state
Mono.Android no iOS.

If I get pass the error about 'not sure which version to use' an exception
is throw inside Refit somewhere - it makes no attempt to contact my servers.

I'm all ears on how to correctly use Refit with Xamarin.  I spent around 6
hours today trying to get it to work but don't know how to debug inside
Refit from within XS so can not really see why it is failing.

Do you use XS or Visual Studio?

Many thanks

Paul

On 27 January 2015 at 18:13, Paul Betts <notifications@github.com> wrote:

> I think you're misunderstanding me. When you open your "References" on
> your project, do you see a reference to "monotouch" or to "Xamarin.iOS"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paulcbetts/refit/issues/125#issuecomment-71697829>.
>



-- 
Lincolnshire Holiday Cottages <http://rigsbywoldholidaycottages.uk/>

**Comment by readiescards** [comment]
Still plugging away at trying to get Refit to wake but I think the issue is
in ModernHTTPClient. As just tried running: ModernHttpClient
<https://github.com/paulcbetts/ModernHttpClient>/samples
<https://github.com/paulcbetts/ModernHttpClient/tree/master/samples>/*HttpClient.Android
 and get the same issue. Namely an unhandledException when I try to access
a server on the LAN (http://127.0.0.1:22005 <http://127.0.0.1:22005>).
Happens both on KitKat 4.4 running on AndroidPlayer or a real Nexus 5
running Android 5.0. *

*Does ModernHTTPClient work with XS? *

On 27 January 2015 at 22:06, Paul Read <paul@readiescards.co.uk> wrote:

> Hi Paul
>
> I'm trying with a basic PCL based Android app - so references just state
> Mono.Android no iOS.
>
> If I get pass the error about 'not sure which version to use' an exception
> is throw inside Refit somewhere - it makes no attempt to contact my servers.
>
> I'm all ears on how to correctly use Refit with Xamarin.  I spent around 6
> hours today trying to get it to work but don't know how to debug inside
> Refit from within XS so can not really see why it is failing.
>
> Do you use XS or Visual Studio?
>
> Many thanks
>
> Paul
>
> On 27 January 2015 at 18:13, Paul Betts <notifications@github.com> wrote:
>
>> I think you're misunderstanding me. When you open your "References" on
>> your project, do you see a reference to "monotouch" or to "Xamarin.iOS"?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/paulcbetts/refit/issues/125#issuecomment-71697829>.
>>
>
>
>
> --
> Lincolnshire Holiday Cottages <http://rigsbywoldholidaycottages.uk/>
>



-- 
Lincolnshire Holiday Cottages <http://rigsbywoldholidaycottages.uk/>

**Comment by readiescards** [comment]
FYI as before no connection is made to the actual server.  Does
ModernHTTPClient support LAN connections over specific ports?

On 28 January 2015 at 19:59, Paul Read <paul@readiescards.co.uk> wrote:

> Still plugging away at trying to get Refit to wake but I think the issue
> is in ModernHTTPClient. As just tried running: ModernHttpClient
> <https://github.com/paulcbetts/ModernHttpClient>/samples
> <https://github.com/paulcbetts/ModernHttpClient/tree/master/samples>/*HttpClient.Android
>  and get the same issue. Namely an unhandledException when I try to access
> a server on the LAN (http://127.0.0.1:22005 <http://127.0.0.1:22005>).
> Happens both on KitKat 4.4 running on AndroidPlayer or a real Nexus 5
> running Android 5.0. *
>
> *Does ModernHTTPClient work with XS? *
>
> On 27 January 2015 at 22:06, Paul Read <paul@readiescards.co.uk> wrote:
>
>> Hi Paul
>>
>> I'm trying with a basic PCL based Android app - so references just state
>> Mono.Android no iOS.
>>
>> If I get pass the error about 'not sure which version to use' an
>> exception is throw inside Refit somewhere - it makes no attempt to contact
>> my servers.
>>
>> I'm all ears on how to correctly use Refit with Xamarin.  I spent around
>> 6 hours today trying to get it to work but don't know how to debug inside
>> Refit from within XS so can not really see why it is failing.
>>
>> Do you use XS or Visual Studio?
>>
>> Many thanks
>>
>> Paul
>>
>> On 27 January 2015 at 18:13, Paul Betts <notifications@github.com> wrote:
>>
>>> I think you're misunderstanding me. When you open your "References" on
>>> your project, do you see a reference to "monotouch" or to "Xamarin.iOS"?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/paulcbetts/refit/issues/125#issuecomment-71697829>.
>>>
>>
>>
>>
>> --
>> Lincolnshire Holiday Cottages <http://rigsbywoldholidaycottages.uk/>
>>
>
>
>
> --
> Lincolnshire Holiday Cottages <http://rigsbywoldholidaycottages.uk/>
>



-- 
Lincolnshire Holiday Cottages <http://rigsbywoldholidaycottages.uk/>

**Comment by readiescards** [comment]
ignore the above, was simple missing understanding in networking access
