### ISSUE TITLE
Refit problems with Windows Phone

### ISSUE THREAD

**Issue by jovanpaskota** [paulcbetts/refit#129]
Using refit for an Xamarin Forms application and it does not give me problems on iOs but when running on Windows Phone simulator or device i get:  Could not load file or assembly 'Refit, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly.

/Jovan

**Comment by promontis** [comment]
Noticed this myself too... The fix has been pushed recently. Was something with assemblyinfo. Anyhow, you can build the latest source yourself or wait for the nuget push

**Comment by jovanpaskota** [comment]
Thank You, will try to build and see if it works.

**Comment by ahmedalejo** [comment]
@jovanpaskota any update on this, so issue could be closed.

**Comment by Cheesebaron** [comment]
Works fine in my Windows Phone 8.1 project.
