### ISSUE TITLE
Using JsonProperty  -> Newtonsoft.Json.Serialization.JsonProperty' is not an attribute class

### ISSUE THREAD

**Issue by gramlin** [paulcbetts/refit#130]
Refit 2.2.1;
I'm trying to use deserialization conversion using JsonProperty based on the example in the Readme. 
Eg;
public class Foo 
{
    // Works like [AliasAs("b")] would in form posts (see below)
    [JsonProperty(PropertyName="b")] 
    public string Bar { get; set; }
} 

Which will bork the compiler with a; 
Newtonsoft.Json.Serialization.JsonProperty' is not an attribute class

**Comment by vzsg** [comment]
The correct name of the JsonProperty attribute is `Newtonsoft.Json.JsonPropertyAttribute`, but in C# they look the same. You probably imported the wrong type.

Try removing `using Newtonsoft.Json.Serialization;` and adding `using Newtonsoft.Json` instead.

**Comment by gramlin** [comment]
Ah. Off course (or DOH!)! 

Doh.

**Comment by mariegithub** [comment]
Thanks !!!!
