### ISSUE TITLE
Refit does not build in TeamCity

### ISSUE THREAD

**Issue by pkl728** [paulcbetts/refit#133]
I have a Xamarin project in which I am making use of Refit.  Lovely library by the way!

The problem I seem to be having is that TeamCity can not find InterfaceStubGenerator.exe.  My log looks like so:

```
/Library/Frameworks/Mono.framework/Versions/3.12.0/lib/mono/4.5/Microsoft.Common.targets: error : Command '"../packages/refit.2.2.1/tools/InterfaceStubGenerator.exe" "/Library/TeamCity/buildAgent/work/f3ff4287feddfdb3/MyApp.Core/RefitStubs.cs" "<List of files in Project>"' exited with code: 127.
```

For brevity I replaced my full list of files with "List of flies in project" above.

I believe this has to do with the Pre-build event that is being set on my core project.  This compiles and works just fine in Visual Studio however I am getting that error when my TeamCity server attempts to build and run my unit tests on a Mac Mini.

I've confirmed that InterfaceStubGenerator.exe exists in /packages/refit2.2.1/tools/.

Any ideas?

**Comment by paulcbetts** [comment]
We're using `$(SolutionDir)` in the targets file, I'm not sure how that is getting set incorrectly. You probably need to write a custom shell script that makes sure you're in the solution root when you invoke `mdtool`

**Comment by pkl728** [comment]
I was able to solve this for the time being by doing this:

```
  <PropertyGroup>
    <PreBuildEvent Condition=" '$(OS)' == 'Windows_NT' ">
	"$(SolutionDir)packages\refit.2.2.1\tools\InterfaceStubGenerator.exe" "$(ProjectDir)RefitStubs.cs" "@(Compile)"
    </PreBuildEvent>
    <PreBuildEvent Condition=" '$(OS)' != 'Windows_NT' ">
	cd $(ProjectDir);mono --runtime=v4.0 "$(SolutionDir)packages\refit.2.2.1\tools\InterfaceStubGenerator.exe" "$(ProjectDir)RefitStubs.cs" "@(Compile)";cd $(SolutionDir)
    </PreBuildEvent>
  </PropertyGroup>
```

Not sure if it would be useful to pull that kind of thing into your library as the conditionals might need to be more verbose...

**Comment by paulcbetts** [comment]
I think I can actually fix this a different way

**Comment by pkl728** [comment]
That just might do it!

**Comment by onovotny** [comment]
@paulcbetts Keep in mind that the binary location will be changing soon to a user-wide/machine cache. Don't assume that it'll be in SlnDir\Packages\blah for long.

The real location may be c:\users\foo\appdata\local\nuget\blah and brought into the csproj via a variable.

**Comment by keannan5390** [comment]
are there any updates to this yet? I ran into this today and it is a bit of a blocker for my project.

**Comment by decriptor** [comment]
This seems to work as long as you don't pass it a project instead.. or at least that seems to be what is happening. If I use fake and try to package an android app using the csproj file instead I get this:
Command 'mono "/packages/refit.2.2.1/tools/InterfaceStubGenerator.exe"

**Comment by ianrathbone** [comment]
I sorted this by changing the pre build event command line to:
`if '$(BuildingInsideVisualStudio)' == 'false' "$(SolutionDir)\packages\refit.2.2.1\tools\InterfaceStubGenerator.exe" "$(ProjectDir)RefitStubs.cs" "@(Compile)"`

**Comment by Gaisuru** [comment]
Is there a proper fix for this yet? I have tried some on the "solutions" in here and I get the error code 255, meaning I hit the character limit.

**Comment by onovotny** [comment]
Closing as 3.x should fix this. Please re-open if still an issue.
