### ISSUE TITLE
Mustache Template

### ISSUE THREAD

**Issue by Odonno** [paulcbetts/refit#134]
Hi,

I've tried to update the Mustache Template file but when I build my project, the RefitStubs is regenerated but is still the same...

Do I need to do more than updating *.mustache file ?

**Comment by bennor** [comment]
Can you show us what changes you have made, and the `RefitStubs.cs` that is generated?

**Comment by BrianSakhai** [comment]
I'm don't know what changes Odonno was making, but I am having the same issue.

I am only adding `// <auto-generated />` to the beginning of the template.
