### ISSUE TITLE
Content-Type header attribute on method doesn't apply correctly

### ISSUE THREAD

**Issue by smoy** [paulcbetts/refit#136]
```
[Post("/store")]
[Headers("Authorization: Bearer", "Content-Type: application/json; charset=UTF-8")]
Task<string> InsertItem([Body] string content);
```

The above snippet doesn't seem to apply `application/json` to the content header.

I have to resort to the following work around

```
[Post("/store")]
[Headers("Authorization: Bearer")]
Task<string> InsertItem([Body] string content, [Header("Content-Type")] string contentType);
```

Now, it seems whatever I pass into contentType is apply to the content header.

**Comment by bennor** [comment]
Will fix this today or tomorrow.

**Comment by muhammetsahin** [comment]
Hi,

I've tried

	[Post ("/route/execute")]
		[Headers("Authorization: Bearer","Content-Type: application/json; charset=UTF-8")]
		Task<PropertyDto> GetProperty ([Body(BodySerializationMethod.Json)] Dictionary<string, object> data,string accessToken);

and tried this,

	[Post ("/route/execute")]
		[Headers("Content-Type: application/json; charset=UTF-8")]
		Task<PropertyDto> GetProperty ([Body(BodySerializationMethod.Json)] Dictionary<string, object> data,[Header("Authorization: Bearer")] string accessToken);

data value is:

var data = new Dictionary<string, object> {
				{"Controller","Property" }, 
				{"Action", "List"},
				{"Method", "GET"},
			};

WEB API:


Url
http://appapi.xxxx.com/api
Content-Type
application/json
Authorization
Bearer e7LFtHMK3Ru84CZWzy9OIOnQMQPm7DIanNEdI85sacGO29QR4jqmVz5oQ1ckaJmr39KS2S96i4bX5iYnjnbSRRNddT0noRHP_1UI8Aq6zT__H0m2Ip7wirMzDBKa_A7zCZztRnVfj9llipOWWU7s9MHzxh_mO3hmaUOZHGGPMWcqfx5QUvcNVNz6OjCgAp8lFBEucENBDHa3endey7la0tEmPCiCZdpMJN5ol75oALGR1tuhJ05eYT2KLRlgzR41TlQZ6J-sn-qJcXIq552P5g
Raw
{"Controller":"Property","Action":"List","Method":"GET"}

But I've got error:

500 Internal Server Error 

Note: access token is not  correct. it is sample accesstoken.

**Comment by bennor** [comment]
@muhammetsahin - although this seems like the same bug, it's totally different to what @smoy raised (and we fixed).

Looking at your description, it doesn't seem as though Refit is the problem here -- the `Content-Type` header is being set to `application/json` in the request. (It's possible that there _might_ be a bug stripping the `; charset=UTF-8` out, but given we're using standard HttpClient methods to set the headers, that's unlikely. (A missing charset in the content type header is unlikely to be the source of the problem anyway, unless you're trying to get JSON back from an ASMX web service.)

Is the API on your server? If so, can you give a bit more detail than "Internal Server Error"?

**Comment by muhammetsahin** [comment]
@bennor 

Changed code like this:

[Post ("/route/execute")]
		Task<PropertyDto> GetProperty ([Body(BodySerializationMethod.Json)] Dictionary<string, object> data,[Header("Authorization")] string accessToken);

![image](https://cloud.githubusercontent.com/assets/2045788/9847532/420230f8-5ae2-11e5-8abc-dc289ddee081.png)

**Comment by muhammetsahin** [comment]
I solve my problem :)

[Post ("/route/execute/")]
		Task<PropertyDto> GetProperty ([Body(BodySerializationMethod.Json)] Dictionary<string, object> data,[Header("Authorization: Bearer")] string accessToken);


This code did work but when i changed and call like this it worked.

[Post ("/route/execute/")]
		Task<PropertyDto> GetProperty ([Body(BodySerializationMethod.Json)] Dictionary<string, object> data,[Header("Authorization")] string accessToken);

var data = new Dictionary<string, object> {
				{"Controller","Property" }, 
				{"Action", "List"},
				{"Method", "GET"},
			};

	var property =await propertService
				.GetPropertyList (data, "Bearer "+account.AccessToken);

I dont know is this bug or not but finally solved :+1: thanks.

**Comment by bennor** [comment]
I wondered if it had something to do with the auth header. There's no magic involved there - you need to specify the whole header value. It's not smart enough to tell that you're passing in a bearer token, so it makes sense you'd need to add `"Bearer "` to the start of your `accessToken` string.
