### ISSUE TITLE
Constants is not working with Get attribute

### ISSUE THREAD

**Issue by hamzamayet** [paulcbetts/refit#140]
using System.Threading.Tasks;
using Refit;

public interface IUser
    {

        // This works fine
        [Refit.Get("/api/users")]
        Task<User> GetUsers();

        // ERROR (If i use constant in Get it throws an error)
        //[Refit.Get(Constants.RouteNames.GetUsers)]
        //Task<User> GetUsers();

    }

**Comment by bennor** [comment]
:joy: I looked into this before and allowing constants will either run the risk of detecting _non-Refit_ attributes as Refit ones or be really nasty to implement.

I can have a look at this, but I'm not sure what the value in moving your routes to a file full of constants is anyway? Wouldn't it be better to have them displayed there next to the method so you don't have to jump between files to figure out what the route actually is?

**Comment by paulcbetts** [comment]
I agree that this should be technically possible, but it's way too hard, sorry
