### ISSUE TITLE
SSL peer shut down incorrectly Windows Phone 8.1

### ISSUE THREAD

**Issue by jfreeley** [paulcbetts/refit#142]
Hey guys,

I'm moving a project from Windows Phone 8.0 to 8.1. I'm having some trouble at the minute with refit on WP 8.1. 

For some HttpClient requests, I'm getting a 404 back from Refit and message in Charles is "SSL peer shut down incorrectly". 

The issue only seems to be with System.Net.Http.HttpClient (v4.x) on WP 8.1 not disabling SSL protocal. WP8.0 System.Net.Http.HttpClient (v1.5) works no problem and Windows.Web.Http.HttpClient on WP8.1 also works.

Issue is System.Net.Http.HttpClient is what is generated and I can't seem to find a way of forcing TLS only.

My other thoughts are modding refit for 8.1 to use the Windows.Web.Http.HttpClient instead.

Any thoughts on a solution would be much appreciated..
Has anyone run in to the same problem?.

Thanks
Jeremy

**Comment by paulcbetts** [comment]
Definitely not a Refit bug, but if you're getting a 404 back from the server you're at least getting data back (so I'd look at that Charles message as a red herring). I'd check the requests you're posting.
