### ISSUE TITLE
POST methods doesn't work on Windows Phone 8.1 App

### ISSUE THREAD

**Issue by wassim-azirar** [paulcbetts/refit#143]
I'm trying to create some Refit methods for the Gitter API.

Implementing the **GET** methods worked just fine, but when I tried a POST method I got an 404 exception.

I translated this Rest API method :

```
POST /v1/rooms/:roomId/chatMessages
Parameters
text: Required body of the message.
```
Into this :

```csharp
[Post("/rooms/{id}/chatMessages")]
Task<Message> SendMessage([AliasAs("id")] string roomId, [Body] string text, [Header("Authorization")] string accessToken);
```

**"Response status code does not indicate success: 400 (Bad Request)."**

A first chance exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.ni.dll
A first chance exception of type 'System.Net.WebException' occurred in System.Net.ni.DLL
A first chance exception of type 'Refit.ApiException' occurred in Refit.DLL
A first chance exception of type 'Refit.ApiException' occurred in mscorlib.ni.dll
A first chance exception of type 'Refit.ApiException' occurred in mscorlib.ni.dll
The thread 0x898 has exited with code 0 (0x0).

You can find the full source code in my Github [Repository](https://github.com/wassim-azirar/GitterClient/)

**Comment by wassim-azirar** [comment]
This how a made it to work with Refit [Link](https://github.com/wassim-azirar/GitterClient/blob/master/GitterClient/Api/IGitterApi.cs)

**Comment by mattiasnordqvist** [comment]
Is the PUT method working in your link?

**Comment by wassim-azirar** [comment]
Yep :)

**Comment by robertohuertasm** [comment]
I have the same issue. I'm getting this weird message when dealing with Windows Phone Silverlight 8.1. Any ideas on how to solve it? What's the cause of this?
