### ISSUE TITLE
Stub generation failure when building with many files ('path too long')

### ISSUE THREAD

**Issue by erickok** [paulcbetts/refit#148]
We are building a reasonably sized application (Universal App, with Shared, a Win and a Win Phone project) and Refit is great. Recently however the stubs can no longer be generated and our build fails.

When building, Refit needs to generate the RefitStubs.cs file by calling InterfaceStubGenerator.exe. This supplies as its argument ALL files in the project. For files in linked projects all files are given by their full path. This causes the argument to the InterfaceStubGenerator.exe to be too long (255 characters allowed) and Visual Studio stops the build.

Here is the full error given (with trucated argument for all our files, for readability):
```1>  
1>  Unhandled Exception: System.NotSupportedException: The given path's format is not supported.
1>     at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
1>     at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
1>     at System.IO.FileInfo..ctor(String fileName)
1>     at Refit.Generator.Program.<>c__DisplayClass6.<Main>b__0(String x)
1>     at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
1>     at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
1>     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
1>     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
1>     at Refit.Generator.Program.Main(String[] args)
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1247,5): 
error MSB3073: The command ""C:\Dev\Leclerc-Compagnon-Win\Compagnon\packages\refit.2.2.1\tools\InterfaceStubGenerator.exe" 
"C:\Dev\Leclerc-Compagnon-Win\Compagnon\Compagnon\Compagnon.Windows\RefitStubs.cs" 
"Pages\AllCategories.xaml.cs;Pages\Products\Product.xaml.cs;Pages\Products\Catalog.xaml.cs;  ...LOTS OF FILES HERE... "" exited with code 255.
```

Is there a solution or workaround? If needed, can I temporarily disable the calling of the InterfaceStubGenerator.exe?

**Comment by srozga** [comment]
Running into this same issue as well.

**Comment by onovotny** [comment]
One fix for this would be to write the file parameters to a temp file in the intermediate dir (one file per line, etc) and then pass that temp file as the parameter. I will aim to create said fix

**Comment by onovotny** [comment]
This should be fixed as part of https://github.com/paulcbetts/refit/pull/153 whenever that gets merged in.

**Comment by erickok** [comment]
Thanks! Will check when this gets merged.

**Comment by gamicklisafisher** [comment]
For deletion or handling of long name i check that "Long Path Tool" software should be try, many articles refer this for such solutions.

**Comment by brad007** [comment]
facing the same problem after pulling my project from git. failed to build on xamarin studio
