### ISSUE TITLE
CustomHttpClientHandler vs ModernHttpClient

### ISSUE THREAD

**Issue by paulyoung** [paulcbetts/refit#150]
I'm wondering if it's possible to use ModernHttpClient in conjunction with the technique described in the README regarding setting authorization headers via a custom handler:

https://github.com/paulcbetts/refit#authorization-dynamic-headers-redux

**Comment by Cheesebaron** [comment]
Duplicate of #42

**Comment by paulyoung** [comment]
Thanks @Cheesebaron!
