### ISSUE TITLE
RefitStubs.cs generate code not working

### ISSUE THREAD

**Issue by rinlv** [paulcbetts/refit#151]
Hi,
I'm using refit to connect to API services. My code is still working before I commit it to svn. Then i build my project in another computer, my application crash when connect API service, and i see RefitStubs.cs doesn't have generated code. How to fix it?
Thanks.

**Comment by bennor** [comment]
How are you building it? Do you have errors or warnings in your build log?

You either need to ensure your build regenerates it, or check the one generated at dev time in to SVN.

**Comment by bennor** [comment]
How are you building it? Do you have errors or warnings in your build log?

You either need to ensure your build regenerates it, or check the one generated at dev time in to SVN. The NuGet package makes some changes to your project file. Are you sure you checked that in?

**Comment by rinlv** [comment]
I'm building without errors. But when i connect API service it crash. I have checked .csproj and see no change. zz

**Comment by rinlv** [comment]
﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

There are code genarated in RefitStubs.cs

**Comment by rinlv** [comment]
I'm fixed this. Error cause I use const in interface instead of hard code string.
Thanks for your support
