### ISSUE TITLE
Warning CS1701 after updating Newtonsoft.Json to 7.0.1

### ISSUE THREAD

**Issue by paulyoung** [paulcbetts/refit#157]
I started receiving this warning in a C# project after Xamarin Studio notified me that there was an update available for Newtonsoft.Json

```
Warning CS1701: Assuming assembly reference `Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' matches assembly `Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. You may need to supply runtime policy (CS1701)
```

**Comment by yozzozo** [comment]
I get this same error too.

**Comment by Cheesebaron** [comment]
Looking at the config files. It seems like Refit is using Version 6.0.0.5 of Newtonsoft.Json. This might need an upgrade at some point.

**Comment by Macjon** [comment]
It would be very nice if you merge the PR from martijn00. I need the update of the newtonsoft.json for a project I'm working on.

**Comment by onovotny** [comment]
Uses 9.0.1 currently
