### ISSUE TITLE
Setting multipart stream field name

### ISSUE THREAD

**Issue by mikeyoon** [paulcbetts/refit#160]
I'm trying out the new multipart feature, and I noticed there's no way to set the a file's field name or disposition type. The following change will probably work in my case when using a FileInfo:

``` C#
var fileInfoValue = itemValue as FileInfo;
if (fileInfoValue != null) {
    var fileContent = new StreamContent(fileInfoValue.OpenRead());
    fileContent.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data") { //changed disposition type to form-data
        FileName = fileInfoValue.Name,
        Name = itemName //Added itemName here
    };
    multiPartContent.Add(fileContent); 
    return;
}
```

But that does leave a gap for the Stream or byte[] and there's currently no attribute for setting the disposition type. I think AliasAs could be obeyed for multipart files to solve the name issue, but maybe the AttachmentName attribute needs to be expanded to support disposition type. I can add that and make a PR if that sounds good, but I'm open to other ideas.

**Comment by TheTekton** [comment]
That would work for where multipart w/Refit isn't working for me, I think. (API expects name="image" in this particular case.) Was thinking that might be a good PR too.

**Comment by TheTekton** [comment]
Okay, so while I'm not sure if what I've done locally to work around this is the best way, but made a gist to explain it nevertheless (checked out 2.3.0 as couldn't get latest commit to build locally [and had to disable monodroid due to System.Object reference error in 2.3.0 and latest Xamarin Studio stuff]):

https://gist.github.com/TheTekton/0eebf4600743564d7ba3

Created a Name attribute (wasn't sure of what to call it more specifically, in a hurry), then built it out like the AttachmentName attribute. When the Name attribute is empty, it's not used. Only testing byte[], here, but can't think of any reason why it might break the other supported types. Anyways, perhaps something for more discussion, but deferring PR for more feedback as well (even if what I have works, doubt the naming of things is exactly kosher).

**Comment by kerr23** [comment]
I'm wondering if this is similar to my issue.
When trying to post to a service and my post looks like:
```POST http://places/service/v1/upload/ HTTP/1.1
Content-Type: multipart/form-data; boundary="----MyGreatBoundary"
Content-Length: 48636
Expect: 100-continue
Connection: Keep-Alive

------MyGreatBoundary
Content-Disposition: attachment; filename=stream
<binary data>
------MyGreatBoundary--```

What my service is expecting, and what I think is reasonable here is something more like:
(In the body)
```
------MyGreatBoundary
Content-Disposition: form-data; name="file"; filename="thefuture.jpg"
Content-Type: image/jpeg
<binary data>
------MyGreatBoundary
```

Does this match up with what you're seeing and trying to solve in that gist? if so - then I'd love to see a PR.

**Comment by mikeyoon** [comment]
@kerr23 That is the exact issue I had. The REST API provided needed the "name" field set for each multipart. I was looking into making a PR, but I had difficulty figuring out a good API for setting multipart information that matched up with the existing code in RequestBuilder.

**Comment by kerr23** [comment]
Yeah, i didn't see an easy way to make it happen either. I ended up building my own client w/o refit.

**Comment by vinishiru** [comment]
Is there already a way to set the field name of a byte[] parameter?
I've tried the [AliasAs] attribute but seems that it's not respected when using [AttachmentName] attribute.

**Comment by Dylanvdb** [comment]
Still no fix for this? Our API also expects a name for the byte[] parameter but the [AliasAs("name")] does not work.

**Comment by onovotny** [comment]
I thought I checked in a fix for this. I def have it working for my SignClient, I'll get an update published.

Sent from my Windows 10 phone

**Comment by Dylanvdb** [comment]
@onovotny Thanks! I'm using version 2.4.1 btw because I can't add the 3.0.1 version to my PCL. Or is the fix only in the 3.0.x versions?

**Comment by onovotny** [comment]
It will be, but what’s holding you back? What pcl profile are you targeting?

Sent from my Windows 10 phone

**Comment by Dylanvdb** [comment]
@onovotny PCL 4.5 - Profile111, which one should it be working with?

**Comment by Dylanvdb** [comment]
@onovotny Ok, I've updated my pcl profile and refit is now on version 3.0.1 but the [AliasAs] still isn't working

**Comment by onovotny** [comment]
Any version you can install a netstandard library into :) You should be able to install Refit 3.0.1 into a Profile 111 according to this chart in the PCL compat section:
https://docs.microsoft.com/en-us/dotnet/articles/standard/library#comparison-to-portable-class-libraries

I've verified the fix is in 3.0.1
https://github.com/paulcbetts/refit/commit/4a8c5eebc23078afbe0a62fa075f66f71d49fe45

It should be using the parameter name as the "name" element for multipart. The easiest use is if you use a FileInfo object, then it'll take the parameter name and the filename all together. 

Can you try the 3.0.1 version; does that work for you?

**Comment by Dylanvdb** [comment]
@onovotny Changed the PCL profile to PCL 4.6 - Profile 151 and after updating all refit packages to 3.0.1 it's working now. But other than the image, I also send two strings in the request but they are sent as arrays instead of the string itself. 
To clarify:

**Current code with refit**

    Task<APIResponse<ImageMessage>> SendImageMessageAsync([Header("Authorization")] string token, Guid connectionId, 
    [AliasAs("data[image][file]"), AttachmentName("image.jpg")] byte[] image, 
    [AliasAs("data[type]")] string type, [AliasAs("data[image][caption]")] string caption);

**What the API receives**

    (
        [data] => Array
            (
                [image] => Array
                    (
                        [file] => Array
                            (
                                [name] => image.jpg
                                [type] => 
                                [tmp_name] => /srv/users/serverpilot/tmp/phpvDHNQf
                                [error] => 0
                                [size] => 541348
                            )
                        [caption] => Array
                            (
                                [name] => data[image][caption]
                                [type] => text/plain
                                [tmp_name] => /srv/users/serverpilot/tmp/phpD1C1s7
                                [error] => 0
                                [size] => 8
                            )
                    )
                [type] => Array
                    (
                        [name] => data[type]
                        [type] => text/plain
                        [tmp_name] => /srv/users/serverpilot/tmp/php7fwTEG
                        [error] => 0
                        [size] => 5
                    )
            )
    )

**What I want the API to receive**

    (
        [data] => Array
            (
                [image] => Array
                    (
                        [caption] => This is my image
                        [file] => Array
                            (
                                [name] => image.jpg
                                [type] => 
                                [tmp_name] => /srv/users/serverpilot/tmp/phpvDHNQf
                                [error] => 0
                                [size] => 541348
                            )
                    )
                [type] => IMAGE
            )
    )

**Comment by onovotny** [comment]
Not sure I'm totally following, but if you can create a PR with a failing test (or at least a runscoped version that shows what you're seeing, it'd be much appreciated.

The current tests for mutlipart are here:
https://github.com/paulcbetts/refit/blob/master/Refit-Tests/MultipartTests.cs

**Comment by Dylanvdb** [comment]
@onovotny Let me try to clear it up, 2 of my parameters in the method which I added refit attributes to are strings, but refit sends them as arrays as you can see in the example above. Do you know of a reason this could happen?

Is this clear or do you need a test?

Thanks for the help btw, it is much appreciated!

**Comment by onovotny** [comment]
Are you expecting those as different content parts?

**Comment by Dylanvdb** [comment]
@onovotny I'm not that experienced with C#, is there a way for me to break on code within a package?

**Comment by onovotny** [comment]
One question -- in your api above, did you include the `[Multipart]` attribute? You didn't include it in what you pasted.

**Comment by Dylanvdb** [comment]
@onovotny Oh sorry, yes I did:

    [Multipart]
    [Post("/connections/{connectionId}/messages")]
    Task<APIResponse<ImageMessage>> SendImageMessageAsync([Header("Authorization")] string token, Guid connectionId, 
        [AliasAs("data[type]")] string type, 
        [AliasAs("data[image][caption]")] string caption, [AliasAs("data[image][file]"),
        AttachmentName("image.jpg")] byte[] image );

**Comment by Dylanvdb** [comment]
@onovotny We've decided on changing our api to work with the data we get from refit, thanks for the help anyway!
