### ISSUE TITLE
Xamarin.Forms  Refit upload files problem, for example upload three photo.

### ISSUE THREAD

**Issue by chaozaiai** [paulcbetts/refit#164]
Xamarin.Forms  Refit upload files problem, for example upload three photo. 
 I am using Refit on Github https://github.com/paulcbetts/refit for Interacting with the server data。
 I think it's wonderful and it meets most of my  needs. When I upload a file to the server, I use the following code.

``` csharp
 [Multipart]
 [Post("/")]
 Task<HttpResponseMessage> UploadStream([AttachmentName("test.pdf")] Stream stream);
```

It works.

When I need to upload three files, how do I use the method? If I only have a choice that upload three files One after another，use this code: `UploadStream([AttachmentName("test.pdf")] Stream stream)`?
Sometimes, people need to  upload multiple files at a time. How write this code?
If someone can tell me something about this, I would be very grateful. 

Thanks.

**Comment by Cheesebaron** [comment]
Just add more parameters?

**Comment by bennor** [comment]
You should be able to add a method to your interface with optional paramters:

```csharp
[Multipart]
[Post("/")]
Task<HttpResponseMessage> UploadStream([AttachmentName("file1.pdf")] Stream file1, [AttachmentName("file2.pdf")] Stream file2 = null, [AttachmentName("file3.pdf")] Stream file3 = null);
```

**Comment by CliffCawley** [comment]
@bennor I'm just trying to do multiple upload now but I'm not having much luck because I get the exception: **Multiple complex types found. Specify one parameter as the body using BodyAttribute**

My declaration looks like:
```c#
        [Multipart]
        [Post("/photo/new")]
        Task<PhotoNewApiResponse> PhotoNew(string parentId, [AttachmentName("Photo")]Stream photoStream, [AttachmentName("Thumbnail")]Stream thumbStream);
```

I've tried converting to a custom class, marking it with Body and attributing the properties of the class with AttachmentName, but whenever I mark an argument Body for a Multipart, I get: **Multipart requests may not contain a Body parameter**

What am I doing wrong?

**Comment by CliffCawley** [comment]
Also, I think I found another issue:

If I try to upload just one file using this:

```
[Multipart]
        [Post("/photo/new")]
        Task<PhotoNewApiResponse> PhotoNew(string sessionToken, string parentId, [AttachmentName("Photo")] byte[] photoStream);
```
Both sessionToken and parentId are completely missing from the request. Only the photoStream byte data is sent, but it's encoded as a base64 string and there appears to be no multipart headers included at all.

I wasn't expecting that at all.

**Comment by ggunders** [comment]
Any progress on multiple files. Any way to pass a  array into the interface if the number of files vary.

**Comment by onovotny** [comment]
This is fixed in the latest by supporting `IEnumerable<T>`
