### ISSUE TITLE
Alternate packages location not supported

### ISSUE THREAD

**Issue by batkuip** [paulcbetts/refit#165]
I have  a nuget.config which sets the repositoryPath to somewhere outside the solution folder.  Unfortunately this breaks refit as the refit.targets is expecting packages to be in the default location

`<PreBuildEvent>mono "$(SolutionDir)packages/refit.2.3.0/tools/InterfaceStubGenerator.exe" "$(ProjectDir)RefitStubs.cs" "@(Compile)"</PreBuildEvent>`

It works if I change it to:

`<PreBuildEvent>mono "$(MSBuildThisFileDirectory)../tools/InterfaceStubGenerator.exe" "$(ProjectDir)RefitStubs.cs" "@(Compile)"</PreBuildEvent>`

However not sure what best practice is here.

**Comment by paulcbetts** [comment]
I'd take that PR

**Comment by onovotny** [comment]
This is addressed in #154 and #153

**Comment by batkuip** [comment]
@onovotny path in 359a3d7d7faed0a61a80d067d21aed613ec6d17b looks wrong too me.  If targets is in the build folder then tools is it's sibling folder.  Am I missing something?

**Comment by onovotny** [comment]
The path is right... The targets cannot be directly in a \build folder as targets must always be in a folder with a TFM to work with NuGet v3.

The new .nuspec has the targets in `build\portable-net45+netcore45+wp8+wpa81+monoandroid+xamarin.ios10\`

**Comment by batkuip** [comment]
@onovotny ah ok - that's for your changes.  This PR is just a fix for this specific issue on the current build.

**Comment by onovotny** [comment]
Sure, but that still leaves refit broken for UWP projects. I'd like to fix it all :)

**Comment by paulcbetts** [comment]
I'm not going to support the new NuGet v3, sorry

**Comment by onovotny** [comment]
Can I ask why, it's just a path change?
