### ISSUE TITLE
Way to keep generated classes internal?

### ISSUE THREAD

**Issue by ncruces** [paulcbetts/refit#167]
Hi,

I came across this when trying to use some internal datatypes in my interfaces.

For example:
```
interface IRemoteApi
{
    Task<User> GetUser(string id);
}
````

Here both `IRemoteApi` and `User` are internal. User implements a public `IUser` and I wrap all calls to the interface in methods responsible for caching, etc. So I'd rather not export it.

Doing this gets me a `CS0050: Inconsistent accessibility` in `RefitStubs.cs`. Changing the mustache to make the autogenerated classes internal fixes it.

Would it be possible (and make sense) to make the class internal whenever the interface is internal?

I tried to have a go into it, but I'm having difficulty understanding the CodeAnalysis stuff, so before I go any further, I'd like to have a feel on whether this makes sense (and a PR would be accepted).

**Comment by bennor** [comment]
:+1:

**Comment by ncruces** [comment]
#168 was merged, this can be closed.
