### ISSUE TITLE
Multipart upload issue

### ISSUE THREAD

**Issue by SivanTR** [paulcbetts/refit#169]
When using Refit for uploading multipart data
the following information gets added to the form post. How the receiving end could process it as the receiving end just looks for file and not the additional information. If this is the standard, can you guys provide a way how to handle this on the receiving end.

------MyGreatBoundary
Content-Disposition: attachment; filename=image.tiff

**Comment by Cheesebaron** [comment]
It is not super complicated.

First detect whether the request is a multipart mime type with `Request.Content.IsMimeMultipartContet()`. Now read the stuff with `Request.Content.ReadAsMultipartAsync()`. The resulting `MultipartMemoryStreamProvider` has a `Contents` property which contains your stuff, you can use LINQ to get whatever attachment you need.

So:

```
var provider = await Request.Content.ReadAsMultipartAsync();
var content = provider.Contents.FirstOrDefault(c => c.Headers.ContentDisposition.FileName == "image.tiff");
```

The content can be read into a variable with one of the methods `ReadAsByteArrayAsync()`, `ReadAsStreamAsync()` or `ReadAsStringAsync()`.

```
var imageBytes = await content.ReadAsByteArrayAsync();
```

There might be a better way to do this. Btw. this is in WebAPI.

**Comment by SivanTR** [comment]
Thanks for the explanation. That really helps.

On an Additional note. Is there a way to upload just an image without using Multipart for other scenarios where we could only post an image.

**Comment by nekresh** [comment]
Refit support the Stream type for single file transfer.

**Comment by onovotny** [comment]
Is there any reason not to fix Refit to include the name= parameter of the content? It'll make it much easier to read on the server?

**Comment by onovotny** [comment]
This should be fixed in the latest
