### ISSUE TITLE
Universal Windows (UWP) compatibility

### ISSUE THREAD

**Issue by plokijuma** [paulcbetts/refit#172]
Hello

I have added Refit to my Universal Windows (Windows 10) project with nuget. 
It compiles without any warning, nothing strange at the build output.

I get exception at runtime : "IApiInterface doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project." when i call "var api = RestService.For<IApiInterface>(API_URL);"

I have added just sample codes, nothing extreme things.

I assume that the "AutoGenerated*" class is not being generated.

PS.: I know the UWP is not supported according to readme yet. It would be nice if Refit would work with UWP.

**Comment by Yortw** [comment]
I have Refit working in a UWP app, although in my case the interface and associated types are in a portable class library targeting UWP.The UWP app itself has Refit installed, plus a reference to the portable class library. The UWP app itself contains the code that calls RestService..For<>(url) and it works fine for me. Not sure if this means your issue isn't UWP, or if it's the portable class library that somehow makes the difference.

If you can't get it working in the UWP app directly (I haven't tried), you might like to try moving your Refit stuff to a portable class library and seeing if that gives you a temporary work around until UWP is fully supported. You do still need to call RestService.For in the app though, won't work from the portable class library.

**Comment by RafaelPlantard** [comment]
Any new about refit for UWP, I cannot use on UWP although I have used the @Yortw aproach. Anybody can help me?
