### ISSUE TITLE
Reserved Words as Method Argument Names Cause Problems In Generated Code?

### ISSUE THREAD

**Issue by Yortw** [paulcbetts/refit#180]
So I'm trying to use Refit against an API that has geo-coordinates in it. Unfortunately the API authors decided to shorten the argument names, so they are "lat" and "long" (ugh). "long" is of course a reserved word. It turns out you can declare a parameter with the name "long" by prefixing it with @ i.e

Task DoSomething(long lat, long @long) 
{
}

However the stub generated by Refit doesn't include the @ on the parameter name in the generated code in the stub file, so it fails to compile.

Is there anyway to tell refit that's a reserved word and it should use the @? I was kind of hoping the @ itself would be enough. I guess I can probably work around this with the AliasAs attribute, but it would nice if it 'just worked'.

**Comment by bennor** [comment]
Fix on its way :arrow_up: :smile:

**Comment by Yortw** [comment]
Wow, that is impressive! The cynic in me was expecting a, "so don't do that then. Closed as won't fix" response. Thanks! :smile: :+1: :cool:

**Comment by bennor** [comment]
It's not merged yet and won't be on NuGet for a little while, so in the meantime you'll have to alias or "don't do that" :wink:
