### ISSUE TITLE
Get parameters containing enum values

### ISSUE THREAD

**Issue by nikeee** [paulcbetts/refit#184]
I am trying to use an enum value as a get parameter.
Example:
```C#
enum Foo
{
	Bar = 1,
	Baz = 2
}

//...
[Get("/items")]
Task GetItems(Foo category);

await GetItems(Foo.Baz); // results in: GET /items?category=Baz
```
How do I change this behavior to take `category` as an `int` without actually changing it to `int`? I don't want to lose the enum value constraining/hinting. To be clear: I want the `category` parameter to have the value `2`, not `Baz`.
Is this possible?

**Comment by bennor** [comment]
There's no support for something like that baked into Refit at the moment, but you have a couple of options:

* Just use `int` for your parameters.
* Create a wrapper type to implictly cast for you.

Just using `int` is fairly self explanatory, but obviously has the drawback that you can pass any `int` as an argument.

Creating a wrapper type would go something like this:

```csharp
public class ApiFoo
{
	Foo value;
	
	public static implicit operator ApiFoo(Foo foo)
	{
		return new ApiFoo { value = foo };
	}
        
        // This determines how it's serialized for a url.
	public override string ToString()
	{
		return value.ToString("d");
	}
}

// Now you can do this
[Get("/items")]
Task GetItems(ApiFoo category);

await GetItems(Foo.Baz); // Results in: GET /items?category=2, but you're still restricted to only passing ApiFoo or Foo types.
```

**Comment by nikeee** [comment]
For now, the implicit cast works fine. Hope we get native support for this (using attributes?) in the future.
Thanks.

**Comment by bennor** [comment]
Sorry, you can also do this in a more repeatable way by passing `RefitSettings` that use a custom implementation of `IUrlParameterFormatter` to `RestService.For()`:

```csharp

public class EnumsAsIntegersParameterFormatter : IUrlParameterFormatter
{
	public string Format(object parameterValue, ParameterInfo parameterInfo)
	{
		if(parameterValue == null)
			return null;
			
		var parameterType = Denullify(parameterInfo.ParameterType);
		
		// Option 1) Format only Foo
		if(parameterType == typeof(Foo))
			return ((int)parameterValue).ToString();
			
		// or Option 2) Format all enums
		if(parameterType.IsEnum)
			return ((int)parameterValue).ToString();
			
		return parameterValue.ToString();
	}

	// Just makes sure you have the generic type arg for Nullable<T>
	static Type Denullify(Type type)
	{
		if(type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>))
			return type.GetGenericArguments()[0];
		
		return type;
	}
}

// Use it like this
var settings = new RefitSettings
{
	UrlParameterFormatter = new EnumsAsIntegersParameterFormatter()
};
var api = RestService.For<IApi>("http://someapi.com", settings);
```

The above has two options - either just format enums of type `Foo` as integers, or format all enums as integers. Use whichever works best for you. :smile_cat:

**Comment by nikeee** [comment]
Thats even better. Thanks.
