### ISSUE TITLE
IQueryable / OData Support

### ISSUE THREAD

**Issue by NVentimiglia** [paulcbetts/refit#185]
What support does REFIT have for Odata and IQuerable ? Looking around, it may be supported (but I am not sure).

https://github.com/paulcbetts/refit/issues/20
https://github.com/paulcbetts/refit/pull/11

Ideally I would like an interface such as expressed in the OData client 

https://github.com/object/Simple.OData.Client/wiki/Retrieving-data-matching-search-criteria

Is this already integrated into the project ? If not, what would you suggest I do ?

**Comment by paulcbetts** [comment]
It's not supported at all, sorry

**Comment by bennor** [comment]
If you really wanted to, you could use Refit to connect to an OData API using `[AliasAs]` for any of the `$whatever` parameters and creative use of custom parameter types, but you're not going to get a fluent API with true `IQueryable` support.

**Comment by NVentimiglia** [comment]
@bennor I might just do this. 

What Is most important to me is an was easy  way to pass a search expression to my server. That way I can expose a single IQueryable<T> GetAll() method on my server (instead of a new one for every search case). The [AliasAs] looks like it is great for paging, but does not solve that issue.

Client side, something like this would work

 [Get("/users/")]
 Task<List<T>> GetUsers(Func<T,bool> expression, int take = 25, int page = 1);

Or even this

 [Get("/users/")]
 Task<List<T>> GetUsers(ODataQuery query);

I understand this functionality is probably not included. Any hints on how I could accomplish my goal? Is it possible that my ODataQuery parameter could spit out multiple Parameter Alias's, for instance?

**Comment by bennor** [comment]
Probably your best bet is to write a custom implementation of `IUrlParameterFormatter` and pass it in the `RefitSettings` when you call `RestService.For()`. Then you can look for parameter types that are assignable to `LambdaExpression` and pull the filter parameters out. (You will still need `[AliasAs("$filter")]` for the parameter name.)

**Comment by NVentimiglia** [comment]
@bennor 

Thanks, this is what I needed.

**Comment by janaagaard75** [comment]
Can I find your solution somewhere, @NVentimiglia? I have the same issue as you.
