### ISSUE TITLE
Win10 UWP - URL path must be of the form '/foo/bar/baz'

### ISSUE THREAD

**Issue by fonix232** [paulcbetts/refit#186]
I'm having this issue in a native Win10 project.

The URL is properly formatted, and tracing the issue, it shows that for some reason, in RequestBuilderImplementation.cs, the extraction of the RelativePath does not succeed. It happens no matter what the URL is, as long as it is a valid URL.
 
Has anyone ran into this issue before? I'm on Build 10240.

**Comment by RafaelPlantard** [comment]
How you use the refit c# for UWP @fonix232 ??
Can you help me?

**Comment by fonix232** [comment]
I don't, I can't, because of this error. Otherwise, I'd use it as one uses
it in a generic .Net project.

**Comment by dapullar** [comment]
This happened to me yesterday, you most likely forgot a beginning slash in the path on your interface.

```objc
[Get("users")]
// Should be..
[Get("/users")]
```

If any path in an interface is wrong, this error is thrown.

**Comment by fonix232** [comment]
Indeed that has been the issue. I missed one of the interface beginning slashes (with an API of over 120 calls, it was easy to miss).
