### ISSUE TITLE
After upgrading to ReFit 2.4.0 I am now getting "doesn't look like a Refit interface" when using Xamarin iOS

### ISSUE THREAD

**Issue by PureWeen** [paulcbetts/refit#187]
I downgraded to 2.3.0 and it works but then when I upgrade to 2.4.0 it gives me 

IYourRestService doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.

I have my "Refit interface" in a PCL library and the Refit.g.cs files generates fine when compiling in Visual Studio and Xamarin Studio on Windows ...

But when I try to compile and run the project on Xamarin Studio on iOS it doesn't generate the Refit.g.cs file :-(

**Comment by onovotny** [comment]
Does it create the rsp in the obj dir with the Cs files? Not sure how to debug this as I don't use xam studio.

**Comment by PureWeen** [comment]
No it doesn't create anything in the obj dir ... The only thing in there is the DLL and MDB file for that PCL library :-/   I turned on diagnostics output and the GenerateRefitStubs target never runs :-/  The refit.targets file gets included ... I can see it Import the project but it never runs the target before the CoreCompile... 

I feel like it's related to what Eric was seeing in an issue with the BCL libraries
https://github.com/ericsink/SQLitePCL.raw/issues/48

I removed the BCL target from the proj file and then the Refit target started generating the .cs files :-/

Eric still hadn't really found a resolution for why the BCL target was interfering

**Comment by onovotny** [comment]
So is this a bug in Xamarin Studio? The BCL targets? Where was the BCL targets coming from, Refit doesn't bring them in outside of WP8 where it's required. Not sure what we can do here?

**Comment by PureWeen** [comment]
No idea :-)    It's kind of funny because BCL comes from the HttpClient libraries which I've just been slacking on replacing with Refit ....  

What I did find out though is if I add this guy to the refit.targets

<PropertyGroup>
    <CoreCompileDependsOn>
        $(CoreCompileDependsOn);
        GenerateRefitStubs
    </CoreCompileDependsOn>
</PropertyGroup>

Then everything generates for me :-)

I don't know why BCL causes it to ignore the BeforeTarget :-(   If that seems like an ok thing to add into the targets I can do a pull request real quick

**Comment by onovotny** [comment]
Can you please submit a PR that includes that?
