### ISSUE TITLE
After upgrading to 2.4.0 Multipart doesnt work with multple parameters

### ISSUE THREAD

**Issue by tamirdresher** [paulcbetts/refit#191]
Im getting an exception "Multiple complex types found. Specify one parameter as the body using BodyAttribute"

i think its related to these changes https://github.com/paulcbetts/refit/commit/363c78d51b239fcd3dafb5d003b6b1b9bf53009d

where this check is made
// The body parameter is found using the following logic / order of precedence:
// 1) [Body] attribute
// 2) POST/PUT/PATCH: Reference type other than string
// 3) If there are two reference types other than string, without the body attribute, throw

i think this is only right if the request is not multipart
do you agree?

**Comment by bennor** [comment]
I think this will be fixed by #189.

**Comment by tamirdresher** [comment]
great
thanks!!
