### ISSUE TITLE
After upgrading to OS X El Capitan (10.11) Xamarin.iOS doesn't build

### ISSUE THREAD

**Issue by dationl** [paulcbetts/refit#192]
I can't build my project anymore after upgrading to El Capitan. csrutil is already disabled and the mcs binary is relinked to /usr/bin/mcs (as suggested in the Xamarin Forum). Mono version 4.0.4.4

```/Users/maxgrim/Projects/SuperCoachOnline/packages/refit.2.4.1/build/portable-net45+netcore45+wp8+wpa81+monoandroid+xamarin.ios10/refit.targets: Error: Command 'mono "/Users/maxgrim/Projects/SuperCoachOnline/packages/refit.2.4.1/build/portable-net45+netcore45+wp8+wpa81+monoandroid+xamarin.ios10/../../tools/InterfaceStubGenerator.exe" "obj/Debug//RefitStubs.g.cs" "/Users/maxgrim/Projects/SuperCoachOnline/SuperCoachOnline.Infrastructure.Resilient" "obj/Debug//RefitParams.rsp"' exited with code: 127. (SuperCoachOnline.Infrastructure.Resilient)```

**Comment by dapullar** [comment]
+1

**Comment by dpronk** [comment]
Same error here !

**Comment by paulcbetts** [comment]
@mteper reports that this is a Xamarin bug with 10.11 where `mono` ends up not being in $PATH somehow

**Comment by dationl** [comment]
I resolved the error for now by manually importing the InterfaceStubGenerator and Refit project, referencing to the correct ones without using NuGet.

**Comment by dapullar** [comment]
Temporary fix:
- Open `refit.targets`
- Line 30: `<RefitExecCmd>mono "$(MSBuildThisFileDirectory) ..snip.. </RefitExecCmd>`
- Change mono path to it's absolute location in my case: `/usr/local/bin/mono`
-  Like this: `<RefitExecCmd>/usr/local/bin/mono "$(MSBuildThisFileDirectory) ..snip.. </RefitExecCmd>`

**Comment by mteper** [comment]
Another alternative is to launch Xamarin Studio from the console like this:

 > PATH=$PATH:/usr/locla/bin /Applications/Xamarin\ Studio.app/Contents/MacOS/XamarinStudio

**Comment by Nathan187** [comment]
@mteper Hey Mike, thanks for that....do you know how to execute that using Apple Script?

**Comment by mteper** [comment]
@Nathan187 sorry, AppleScript is not my strong suit (ask/search on SO, I am sure it's not hard).

**Comment by timbrand** [comment]
Same issue here, and starting via de console command works fine, thanks for that.
Has anyone reported this at Xamarin?

**Comment by mteper** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=34564

**Comment by bratsche** [comment]
This seems to be fixed upstream, the commit listed here isn't needed to resolve it anymore.
