### ISSUE TITLE
Expose the whole Dictionary of RestMethodInfo on IRequestBuilder

### ISSUE THREAD

**Issue by TonyGerace** [paulcbetts/refit#203]
Please expose the RestMethodInfo object (readonly) instead of just the Keys from the Dictionary on IRequestBuilder for serialization and service registry reasons.

**Comment by onovotny** [comment]
Can you elaborate on what you're trying to do? I'm going to close this due to age, but if you can provide some specifics, I'd be happy to look into it further.
