### ISSUE TITLE
Serialize query params

### ISSUE THREAD

**Issue by mtman** [paulcbetts/refit#205]
```csharp
interface IClient
{
    [Get("/api/endpoint")]
    Task<Result> GetData(Query query);
}
```

When calling the method, ToString is used instead of the json serializer on `query`.

**Comment by mtman** [comment]
I believe this would be the solution:
`HttpUtility.UrlEncode(JsonConvert.SerializeObject(value));`

**Comment by mburbea** [comment]
You can use a parameter formatter for this?

**Comment by mtman** [comment]
@mburbea Then what would be a formatter that doesn't break simple types?

My proposal:
```csharp
    class DefaultUrlParameterFormatter : IUrlParameterFormatter
    {
        public string Format(object value, ParameterInfo parameterInfo)
        {
            if (value == null)
                return null;
            
            if (parameterInfo.ParameterType.IsPrimitive) //excl. string etc.
                return value.ToString();

            var convertible = value as IConvertible; //incl. string, DateTime etc.
            return convertible != null
                ? convertible.ToString()
                : JsonConvert.SerializeObject(value);
        }
    }
```

Now why this (or similar) shouldn't be the default?

**Comment by bennor** [comment]
I find it pretty hard to believe that there are many APIs out there expecting JSON in their query string parameters. Doesn't seem at all like something we should support.

**Comment by mattiasnordqvist** [comment]
I'm with bennor on this one, but I think it should be possible to change the default behaviour so that you're not locked to ToString. I think it should be possible to provide your own formatters to support your needs. I don't know but maybe you need OData query strings or something.

**Comment by mtman** [comment]
You can use UrlParameterFormatter in settings.

Yeah you're both probably right that it doesn't have that simple solution.

**Comment by KonstantinRyazantsev** [comment]
@mtman just implement ```IFormattable``` by your ```Query``` class
