### ISSUE TITLE
Multiple Method Signatures

### ISSUE THREAD

**Issue by dapullar** [paulcbetts/refit#207]
Multiple method signatures are not supported. Give duplicate key error, I assume you store method names in a dictionary, example: 

``` java
[Get("/photos?restaurant_id={restaurantId}")]
Task<List<RestaurantPhoto>> GetRestaurantPhotos(int restaurantId);

[Get("/photos?category_id={categoryId}")]
Task<List<RestaurantPhoto>> GetRestaurantPhotos(int categoryId);
```

**Comment by Cheesebaron** [comment]
The signatures of the methods are exactly the same, it is not a Refit error...

**Comment by dapullar** [comment]
Sorry, I made a mistake trying to simplify... regardless the signatures don't work.

```java
[Get("/photos?restaurant_id={restaurantId}&category_id={categoryId}")]
Task<List<RestaurantPhoto>> GetRestaurantPhotos(int restaurantId, int categoryId);

[Get("/photos?menu_item={menuItemId}")]
Task<List<RestaurantPhoto>> GetRestaurantPhotos(int menuItemId);
```

**Comment by Cheesebaron** [comment]
Yes, they are stored in a Dictionary: https://github.com/paulcbetts/refit/blob/master/Refit/RequestBuilderImplementation.cs#L40

**Comment by bennor** [comment]
You could argue that it's something we should implement, but the obvious workaround (using different names for your methods) gives you a more expressive interface anyway:

```csharp
[Get("/photos?restaurant_id={restaurantId}&category_id={categoryId}")]
Task<List<RestaurantPhoto>> GetRestaurantPhotosByCategory(int restaurantId, int categoryId);

[Get("/photos?menu_item={menuItemId}")]
Task<List<RestaurantPhoto>> GetRestaurantPhotosByMenuItem(int menuItemId);
```

**Comment by dapullar** [comment]
Agreed, but I was quite confused when I ran into this, it would just be nice to have a more explicit error thrown.

**Comment by bennor** [comment]
We can definitely add something like that.

**Comment by onovotny** [comment]
This is fixed in the latest CI builds.
