### ISSUE TITLE
Critical issue with build configuration [Xamarin.Android]

### ISSUE THREAD

**Issue by tiborebner** [paulcbetts/refit#208]
We use refit in many of our projects with Xamarin. About two weeks ago I started to experience build errors after Xamarin came out with a new Xamarin.Android release. They updated a build target which they claim is compatible with the old one, yet the **GenerateJavaStubs** target kept crashing with unsupported path exceptions ([Bugzilla Ticket](https://bugzilla.xamarin.com/show_bug.cgi?id=35613#c6)). 

On of the symptoms was that a spurious _Androidobj_ folder was created in the project root during build. I traced back the issue to refit and with some advice from the guy at Xamarin ([Comment 24](https://bugzilla.xamarin.com/show_bug.cgi?id=35613#c24)) I patched the _refit.targets_ file (commented out `<IntermediateOutputPath>` in line 10-12). That solved the issue for a while: with Debug configuration the project build as expected. However, I'm still unable to build with Release config. The _Androidobj_ folder keeps reappearing no matter what. Unfortunately I don't have much experience with MSBuild.

It would be great guys if you could fix this issue as soon as possible or at least give me a hint where to look and how to apply a patch because currently this is a critical, stopping problem for us. Of course I'm happy to give all the details necessary to speed up the resolution. 

Thanks!
This is refit 2.4.1 NuGet and Xamarin.Android 6.0 (Windows 7 / Xamarin Studio 5.10)

**Comment by tiborebner** [comment]
OK, I found out that updating NuGet packages triggers the problems. The *refit.targets* file gets reverted to its original version, the *Androidobj* folder is immediately regenerated (with the *sdks.cache* inside) and the erroneous build config persist until I close Xamarin Studio, cure the *refit.targets* file then restart XS again.

**Comment by RickTheHat** [comment]
What did you do to fix this? What do you mean by "cure". I just updated all of my packages and the latest refit package is at 2.4.1 and am getting these errors /obj/Debug//RefitStubs.g.cs(18,18): Error CS0101: The namespace `RefitInternalGenerated' already contains a definition for `PreserveAttribute'

**Comment by RickTheHat** [comment]
Hmm, after uninstalling and re-installing and fiddling around, it looks like I got this error now. Anyone else getting this error and know of a fix? /Library/Frameworks/Mono.framework/Versions/4.2.1/lib/mono/4.5/Microsoft.Common.targets: Error: Command 'mono "/Users/rick/flavortown/packages/refit.2.3.0/tools/InterfaceStubGenerator.exe" "RefitStubs.cs" "MainActivity.cs;Resources/Resource.designer.cs;Properties/AssemblyInfo.cs;RefitStubs.cs;SplashScreen.cs"' exited with code: 1

**Comment by tiborebner** [comment]
You have to comment out these lines in *packages\refit.2.4.1\build\portable-net45+netcore45+wp8+wpa81+monoandroid+xamarin.ios10\refit.targets*
```CSharp
<PropertyGroup>
    <IntermediateOutputPath Condition="$(IntermediateOutputPath) == '' Or $(IntermediateOutputPath) == '*Undefined*'">$(MSBuildProjectDirectory)obj\$(Configuration)\</IntermediateOutputPath>
</PropertyGroup>
```
That's the "cure". These lines redefine some build variables that they shouldn't and, what's more, they do this incorrectly. Another solution would be (on Windows) to change above snippet to this:
```CSharp
<PropertyGroup>
    <IntermediateOutputPath Condition="'$(IntermediateOutputPath)' == '' Or '$(IntermediateOutputPath)' == '*Undefined*'">$(MSBuildProjectDirectory)\obj\$(Configuration)\</IntermediateOutputPath>
</PropertyGroup>
```
I hope this helps.

**Comment by RickTheHat** [comment]
I deleted the refitstubs.cs from all the projects and it I was able to compile.

**Comment by KeithJRome** [comment]
I was able to work around this for now by reordering the Imports in my csproj file to ensure that the Refit targets is processed *after* the Xamarin.Android.CSharp.targets entry.

It breaks because Refit mangles the $(MSBuildExtensionsPath) var, and the CSharp.targets entry uses that. But if you make sure that Refit is processed afterwards, then it doesn't seem to matter.

YMMV of course

**Comment by Pispa339** [comment]
This issue keeps randomly occurring on my project at least once a day. Usually restoring packages resolves the issue, but not this time. None of the solutions described above are helping. Rather frustrating issue
