### ISSUE TITLE
Support for dnx ?

### ISSUE THREAD

**Issue by bilal-fazlani** [paulcbetts/refit#209]
Is it possible to target a dnx application using coreclr ?

**Comment by reicheltp** [comment]
After a first attempt it seems that there are no problems migrating the refit lib to CoreCLR. 

Unfortunately the InterfaceStubGenerator is depending on Nustache (https://github.com/jdiamond/Nustache) which is a .NET 2.0 project. Either someone has to migrate Nustache to CoreCLR or we have to replace the *.mustache file with another generator.

So if we get the generator to CoreCLR we will have made it.

**Comment by bilal-fazlani** [comment]
I myself started porting refit to core clr and got stuck because of Nustache. And now I am down to using httpclients manually in my project.

**Comment by bilal-fazlani** [comment]
Right now an external exe (which is a wrapper around nustache) is being executed from the tools folder of nuget ( AFAIK , but i don't when exactly is it executed ) for the proxy generation. 
I don't know if that's possible on linux.

**Comment by reicheltp** [comment]
The InterfaceStubGenerator is executed right before compiling. This is just a .NET application (currently on .NET 2.0) which can be run on mono or on coreclr as soon as we ported it.
The new project.json format is supporting commands if you declare them as scripts: { prebuild : "do someting" } within the project.json file.

**Comment by bilal-fazlani** [comment]
That makes sense

**Comment by dgee2** [comment]
Hi is there any news on support for dnx/dotnet core?
@paulcbetts it would be good to hear from you on this.

**Comment by paulcbetts** [comment]
@dgee2 I'm not going to implement dnx support. If some PRs it in and it doesn't immediately require me to upgrade every piece of software on my computer, I'll think about it

**Comment by bilal-fazlani** [comment]
Paul is it okay of I fork this, implement dnx , and publish a nuget package
?

**Comment by paulcbetts** [comment]
@bilal-fazlani Sure, thanks for asking. Just make the NuGet package name clear that it's a separate project

**Comment by bilal-fazlani** [comment]
Yes I will. Thank you :)
