### ISSUE TITLE
Add Refit-Portable to project instead of Nuget package

### ISSUE THREAD

**Issue by adrienjeanjean** [paulcbetts/refit#215]
This is not really an issue but a question; I'm trying to make some changes to my fork of Refit and for that removed the Nuget packages from my Core PCL and Xamarin.iOS projects and added references to the Refit-Portable and Refit-Xamarin.iOS10 projects respectively. However, now RefitParams.rsp and RefitStubs.g.cs no longer get created in the obj folders of neither my Core PCL project or Xamarin.iOS project. I tried manually adding the import statement to point to the refit.targets in my .csproj files and copied the InterfaceStubGenerator.exe to a tools folder at the location it gets called but I still get an error that it exits with code 1. It feels like I'm going about this the wrong way. My question really is; what's the correct way to reference the Refit source projects in your projects instead of the Nuget packages? What configurations do I need to make besides just referencing the Refit projects?

I would be very grateful for some assistance in this matter. And if there's a better place to ask these type of question then here, please let me know.

Cheers,
Adrien

**Comment by adrienjeanjean** [comment]
moved question to stackoverlfow.

**Comment by ahmedalejo** [comment]
@adrienjeanjean please add the StackOverflow link for reference
