### ISSUE TITLE
Circuit breaker and retries

### ISSUE THREAD

**Issue by feanz** [paulcbetts/refit#216]
Just want to start a discussion about a feature request.  It would be good if there was an option to support circuit breakers and retry like in libraries such as [Polly](https://github.com/App-vNext/Polly).

I've done something similar before wiring it into an HTTPHandler the the client can use.  This handler takes in a Polly Policy.  You could do this now using Refit setting but I'm wondering if it would be a nice addition to make it simple for users to set some options on the settings object.  

e.g. 

```
new RefitSettings 
{
    RetryPolicy = new RetryPolicy(5)
    CircuitBreakerPolicy = new CircuitBreakerPolicy(2, TimeSpan.FromMinutes(1))
}
```

Is this something you think should go in refit or should it be upto consumers to add this in what do you think?

**Comment by Cheesebaron** [comment]
Why reinvent the wheel again? Why would this be better than just using Polly?

**Comment by feanz** [comment]
Yeah I was thinking that it would use prolly possibly as some additional package that add support in.  

You may be right that it's not something that should be in the main refit package

**Comment by ahmedalejo** [comment]
@feanz this would be a seperate nuget integration package between Refit and Polly,

> PM> Install-Package Refit-Poly
or
> PM> Install-Package Poly-Refit

Refits´ (code) should know nothing of it.

**Comment by feanz** [comment]
Yeah probably the way to go.

**Comment by AndrewBehn** [comment]
a bit late to the party - but my team has done this kind of Polly-Refit integration and it works quite nicely.   We set up exponential backoff (for crappy connections) and exception filtering (for when the request is invalid vs a transient failure) and it works beautifully.

**Comment by bennor** [comment]
Closing because this is old and not really something we want to support ourselves. You can get this behaviour just using Polly.
