### ISSUE TITLE
Gzip decompression on Xamarin.Forms / Android

### ISSUE THREAD

**Issue by dvolvenl** [paulcbetts/refit#217]
I have the following code to create my RestService, which resides in my Xamarin.Forms PCL:

```
var handler = new HttpClientHandler() { AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate };
var client = new HttpClient(handler)  { BaseAddress = new Uri(Settings.BASESERVICEURL) };
var service = RestService.For<IMyApi>(client);
var items = await service.GetItems();
```

When running this on the Xamarin.Android project I get the following error:

```
"Method 'HttpClientHandler.set_AutomaticDecompression' not found."
```

I then decided to change my code to use the ModernHttpClient, which according to all claims has some form of GZIP decompression:

```
  var handler = new NativeMessageHandler();
```

This however, leads to the following error, which essentially means that the response wasn't decompressed before it started parsing to Json:

```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: . Path '', line 0, position 0.
```

My interface definition is configured with the Accept-Encoding header:

```
[Headers("Accept: application/json", "Accept-Encoding: gzip,deflate")]
public interface IMyApi
```

So what should be the correct way of setting this up for Xamarin Forms / Android?

**Comment by ahmedalejo** [comment]
Hi @dvolvenl have you tried not decorating with `[Headers("Accept: application/json", "Accept-Encoding: gzip,deflate")]` this is done automatically when you do the following

    new HttpClientHandler() { AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate };

and 

make sure you installed **Refit** nuget package into your platform specific projects as well,

**Comment by dvolvenl** [comment]
@ahmedalejo This gives me the same error:

    Method 'HttpClientHandler.set_AutomaticDecompression' not found.

It seems that that property is simply not available on Xam.Android. It also sounds kind of strange to remove the Accept-Encoding header from the interface. The Accept-Encoding header on IMyApi tells the service that the client wants to receive Gzip, whereas the HttpClientHandler is to tell the client to be able to decompress it. Seems like both things serve a different purpose.

**Comment by Cheesebaron** [comment]
This is not a Refit issue. Any errors in ModernHttpClient should be reported in the respective repository.

Although I have gzip decompression working with what @ahmedalejo describes in his post. Only by setting `AutomaticDecompression` on the `HttpClientHandler`, no headers manually set, because they are set for you.

**Comment by dvolvenl** [comment]
Do you have that working in a Xamarin.Android project? Because I think the problem is fairly limited to that type of project.

**Comment by ahmedalejo** [comment]
@dvolvenl please confirm you installed the **Refit** package into your Xamarin.Android and Xamarin.iOS and not only in the PCL?

> The Accept-Encoding header on IMyApi tells the service that the client wants to receive Gzip, whereas the HttpClientHandler is to tell the client to be able to decompress it. Seems like both things serve a different purpose

actually thats why its **Auto**Decompression, it to telling the Server about acceptance of Gzip and/or Deflate, and also tell the client to be capable of this decompression.

May the issue is with your PCL profile,, i use "111" and the above just worked for me as expected.

**Comment by dvolvenl** [comment]
Refit is definetly installed in all projects. However, the PCL profile I was using (which apparently is set like that out of the box by Xamarin) was "78". I set it to "111" and now the above code works. The only thing still not working now seems to be the NativeMessageHandler which doesn't decompress the data automatically. Logged a ticket for this in the ModernHttpClient repo.

**Comment by ahmedalejo** [comment]
@dvolvenl :) i remember now that i had to change the profile when i first started to use **Refit** months ago. thats why this didn´t hit at first.
