### ISSUE TITLE
Getting stream content

### ISSUE THREAD

**Issue by paulanthonymorris** [paulcbetts/refit#218]
Just want to make sure I am not missing something here:
I have an API that has a few JSON endpoints but also a few endpoints with small binary files for download. If I expose the binary as a stream as in...
`[Get("/v2/file.db.gz")]
Task<Stream> GetFileAsync();`
or as in...
`[Get("/v2/file.db.gz")]
Task<byte[]> GetFileAsync();`
Refit wants to parse the result as JSON (which of course blows up).
I could get the raw response as in...
`[Get("/v2/file.db.gz")]
Task<HttpResponseMessage> GetFileAsync();`
and then grab the stream or the bytes from `response.Content` in the caller.
Is this The Right Way?

**Comment by bennor** [comment]
As far as I'm aware, `Task<HttpResponseMessage>` is the only way at the moment. A PR for `Task<byte[]>` or `Task<Stream>` support would be pretty easy. :wink:  ([start here](https://github.com/paulcbetts/refit/blob/master/Refit/RequestBuilderImplementation.cs#L340))

**Comment by bennor** [comment]
Nevermind. I overlooked the `HttpContent` support. If you set your return type `Task<HttpContent>`, you should be able to access the stream from the result.

**Comment by paulanthonymorris** [comment]
Thank you. That works well. I can get the bytes/stream without the extra overhead of the whole response.
