### ISSUE TITLE
Are self-signed certs being ignored?

### ISSUE THREAD

**Issue by brunchey** [paulcbetts/refit#219]
I am trying out refit, and I noticed that if I use to to call a service over https that uses a self signed certificate, I don't get any exceptions.  This differs from when I use the httpclient stand-alone, where I have to implement a ServerCertificateValidationCallback method in order to avoid the HttpRequestException that is thrown with the following message.

"The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."

**Comment by bennor** [comment]
There shouldn't be anything ignoring cert validation errors. Can you provide a repro project?

**Comment by brunchey** [comment]
Sorry, after alot of reviewing of other third party libs we found the offender.  

Apologize for wasting your time

**Comment by bennor** [comment]
No problem. These things happen :)
