### ISSUE TITLE
New Feature: Allow consumers to supply their own implementation of IRequestBuilderFactory

### ISSUE THREAD

**Issue by paynecrl97** [paulcbetts/refit#221]
I'm proposing that a new extension point is added in order to allow consumers to supply their own implementation of `IRequestBuilderFactory`.

I've had a look into what would be required and I think I have a solution: https://github.com/paulcbetts/refit/compare/master...paynecrl97:feature/configure_RequestBuilderFactory?expand=1.

I understand that a conscious decision may have been made to protect the consumer from requiring knowledge of this interface, but I think giving consumers the flexibility to choose their own implementation is quite a powerful feature.

If you agree, I can implement as you see fit, or just tidy up and add some tests to the implementation I linked above and prepare a PR.

**Comment by mattiasnordqvist** [comment]
The absence of extensions points like this one is partly why I gave up on ReFit.

**Comment by chillbythewater** [comment]
This would be really useful. Would allow resolution of #179

**Comment by paulcbetts** [comment]
That makes no sense, why would you use the library at all if you want to replace basically the entire thing

**Comment by chillbythewater** [comment]
I don't think the intention was to replace large portions of the library but to provide the ability to use some of those useful features like overloading or inheritance to modify the behaviour.
