### ISSUE TITLE
HttpStatusCode and ActionResult

### ISSUE THREAD

**Issue by doorman02** [paulcbetts/refit#222]
I have the following REST function at my server site
 [HttpPut]
 [Versions("v1")]
 [Route("Test/{id}")]
 public async Task<ActionResult> Test(string id)
 {
            try
            {
                return Ok();
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int) HttpStatusCode.BadRequest;
                throw;
            }
        }

And in Xamarin I have my REFIT interface defined like this

[Put("/Test/{id}")]
Task<HttpStatusCode?> TestAsync(string id);

This works fine but the returned result is always null, would expect to receive HttpStatusCode.OK
Am I doing something wrong?

Thanks!

**Comment by mattiasnordqvist** [comment]
Change Task to Task <HttpResponseMessage>?

**Comment by mattiasnordqvist** [comment]
Seems like github hides less than and greater than characters. Task of HttpResponseMessage is what you want I think.And this not about Refit, this is about the Task library.

**Comment by doorman02** [comment]
Thanks :)
