### ISSUE TITLE
Get "The request requires buffering data to succeed. " error from POST

### ISSUE THREAD

**Issue by jessejiang0214** [paulcbetts/refit#224]
Hi All,

I got this error every POST in Xamarin.Forms, my api is like this
    [Headers("Accept: application/json", "Content-Type: application/json")]
    public interface IPDLiteAPI
    {
        [Post("/MM/MerchantLogin")]
        Task<LoginResponse> LoginAsync([Body]LoginRequestObj loginRequest);

Refit works well with Get, but none of POST can work.

Here is the Error Image 
[Error Image](https://onedrive.live.com/redir?resid=6C98BB8F525FA790!689774&authkey=!AAXRWIXXtwAyBcU&v=3&ithint=photo%2cpng)
Please help, Thanks

**Comment by ahmedalejo** [comment]
You should state the version you´re using and have an interrogation mark some where(i.e a question), it seem you´re affirming and not asking(if not for your "Please help, Thanks" ), but i´ll let it pass.

Refit works well with post indeed i use the following:

```csharp
    public interface IMailClient : IAttachmentManager
    {
        ...
        [Post("/mail/attachments/{id}/Content")]
        new Task<AttachmentDTO> SaveAttachmentAsync(int id, [Body]Stream content, CancellationToken token = default(CancellationToken));
    }
```
notice that this works with stream upload as content body.

**Note**: I use Xamarin.Forms as well(intensively and solely for my mobile applications, i.e 3 and counting), using solely *Refit* with a pre-configured HttpClient;

Now acording to your error message:

![screen shot 2016-03-16 at 2 34 02 pm](https://cloud.githubusercontent.com/assets/7012074/13813389/0b67ed94-eb60-11e5-87a3-cb19815f2508.png)

The error is server side **RedirectKeepVerb**, meaning that your request to endpoint `.../MM/MerchantLogin` 
is being redirected to `http://.../User/SaleTransaction` temporarily as the response status code informs,

So check your WCF service endpoint for any redirection rules, and oh try securing 
your wsdl endpoint `http://service.helpadesi.com/ProcessDonation.svc?singleWsdl`

```csharp
System.Net.HttpStatusCode.RedirectKeepVerb

Equivalent to HTTP status 307. HttpStatusCode.RedirectKeepVerb indicates that the request information is located at the URI specified in the Location header. The default action when this status is received is to follow the Location header associated with the response. When the original request method was POST, the redirected request will also use the POST method.
Value: TemporaryRedirect
```

**Comment by jessejiang0214** [comment]
Hi @ahmedalejo ,

Thanks for your comment. Actually, we do POST with JSON object, so that the [Body]LoginRequestObj is a data model. Do I need to convert it to a Stream?

I will let our web service developer to check the RedirectKeepVerb issue.

BTW, can refit can customer the JSON deserialization component? We found that if the JSON contain some HTML content, refit cannot deserializaion correctly, it will throw some deserialzaiton error. But if we use Json.net solely. It works well, how could this happen?

**Comment by jessejiang0214** [comment]
Hi @ahmedalejo ,

I made a huge mistake, I forgot "/" after login, it should be [Post("/MM/MerchantLogin/")]

**Comment by ahmedalejo** [comment]
lol, very huge indeed(it shouldn´t be).

Json object as body is supported by Refit, if it can contain xml/html snippets you could use

```
JsonSerializerSettings settings = = new JsonSerializerSettings
{
    StringEscapeHandling =  StringEscapeHandling.EscapeHtml
};

var ipdLiteAPI= RestService.For<IPDLiteAPI>(
    "http://service.helpadesi.com",
    new RefitSettings { JsonSerializerSettings = settings });
```
as configured in [this StackOverflow response](http://stackoverflow.com/a/27859777/2263183)

**Comment by jessejiang0214** [comment]
Thanks so much, but I just curious, what's the different from /MM/MerchantLogin/ and /MM/MerchantLogin. Is that  web service things?
