### ISSUE TITLE
Issue with Turkish culture

### ISSUE THREAD

**Issue by ggroot** [paulcbetts/refit#225]
When setting the culture to Turkish I experience the following error:

[ApiException: Response status code does not indicate success: 400 (Bad Request).]
   Refit.<<buildCancellableTaskFuncForMethod>b__2d>d__30.MoveNext() in y:\code\paulcbetts\refit\Refit\RequestBuilderImplementation.cs:345

Every other culture seems to work. Any suggestions?

**Comment by Cheesebaron** [comment]
What does server side say?

**Comment by ggroot** [comment]
The request doesn't make it to the server

**Comment by Cheesebaron** [comment]
Well it is returning Bad Request, so I suspect that it does.

**Comment by mattiasnordqvist** [comment]
What does your code look like?

**Comment by ggroot** [comment]
In the startup of my mvc project i set the culture in the PipelineStage.PostAcquireState using

CultureInfo newCulture = CultureInfo.GetCultureInfo("tr-TR");
Thread.CurrentThread.CurrentCulture = newCulture;
Thread.CurrentThread.CurrentUICulture = `newCulture;

The Refit interface looks like
[Post("/api/{publicationId}/news")]
Task<List<NewsEventViewModel>> GetNews(int publicationId, OverviewOptions options);

The call looks like:
var news = this.ServiceFacade.GetNews(publicationId, options).Result;

And this is where it fails, however if I set the culture to 'nl-NL' it completes the request without an exception.

Could it be some Phil Haack [blogged](http://haacked.com/archive/2012/07/05/turkish-i-problem-and-why-you-should-care.aspx/) about

**Comment by flagbug** [comment]
I'm pretty sure this has nothing to do with Refit, but there's something on your server that is at fault.

Could you try making the request via something like [Postman](https://www.getpostman.com/)  and see if it also happens there?

**Comment by ggroot** [comment]
No exception occurs when I make the request using Postman. 

It also doesn't matter if its a Post or Get, when I use the Turkish culture the request isn't fired. It breaks before that.

**Comment by flagbug** [comment]
> No exception occurs when I make the request using Postman.

So you're getting a  `200 OK` response?

**Comment by ggroot** [comment]
Solved it. It was caused by the character i
In the Regex.replace used in the buildRequestFactoryForMethod method we need to extend the regexOptions with RegexOptions.CultureInvariant.

My parametermap had the param 'publicationid' which couldn't be replaced with the right value.

**Comment by ggroot** [comment]
Just to be complete:

if (restMethod.ParameterMap.ContainsKey(i))
{
	urlTarget = Regex.Replace(
		urlTarget,
		"{" + restMethod.ParameterMap[i] + "}",
		settings.UrlParameterFormatter.Format(paramList[i], restMethod.ParameterInfoMap[i]),
		RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
	continue;
}

**Comment by flagbug** [comment]
@ggroot Can you submit a Pull Request?

**Comment by onovotny** [comment]
@ggroot can you please submit the change as a PR to this repo? I'd be happy to merge it.

Thanks!

**Comment by onovotny** [comment]
Actually, just did it here #268

**Comment by onovotny** [comment]
Fixed
