### ISSUE TITLE
Refit does not correctly Encode response strings sometimes

### ISSUE THREAD

**Issue by thefex** [paulcbetts/refit#228]
I will make a PR in a minutes. The response I get from one of production API cannot be deserialized - exception "Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: . Path '', line 0, position 0" is thrown. 

I think it is because of some invalid content encoding. I will attach a fix in minutes - I can PM you link to API which crash - it is not public API.

**Comment by Denaindra** [comment]
HI @thefex ,
I also getting the same issue when rendering the image from a service. may I know which service fixed this issue?
