### ISSUE TITLE
Support for getting response headers

### ISSUE THREAD

**Issue by ray2k** [paulcbetts/refit#23]
(This issue is at the request of @paulcbetts over twitter, in which I stated I'm willing to give a pull req a try, but some discussion on scenarios first.)

I would like to see support for getting response headers out of the remote api call while still using a strongly typed response (or none at all). This would be for making calls against APIs (ex the azure management api) that return a unique request-id as a response header, which can be used in support cases when something unexpected/bad happens, or more frequently in the case of asynchronous calls in which a call is made against the api such as swapping an azure deployment, in order to take that returned request-id and query its status in a future api call. 

Given the way refit is exposed to it's user, the most natural way I feel would be to use attributes i.e.

``` C#
// async api that returns no body
[Post("/some/asyncapi/{someId}")]
Task SomeAsyncRemoteApiCall(int someId, [ResponseHeader("x-request-id")] out string requestId);

// async api that returns body and requestid header
[Post("/some/asyncapi/{someId}")]
Task<SomeResponse> SomeAsyncRemoteApiCall(int someId, [ResponseHeader("x-request-id")] out string requestId);
```

I suppose that an alternative to the first one could be

``` C#
[Post("/some/asyncapi/{someId}")]
[return: ResponseHeader("x-request-id")]
Task<string> SomeAsyncRemoteApiCall(int someId);
```

where the returned Task<string> is for the header, not the string content because the request doesn't return a body. But that seems a little wonky IMO.

Thoughts/comments/insults?

**Comment by fonix232** [comment]
Any update on this? I'm in need of retrieving headers for a project, where a CSRF Token is returned via the header in the response.

**Comment by martingemme** [comment]
I would be too interested to have the status code.

**Comment by onovotny** [comment]
The latest code in `master` supports returning an `HttpResponseMessage` object and that would contain the headers.
https://github.com/paulcbetts/refit/blob/master/Refit/RequestBuilderImplementation.cs#L318

**Comment by bennor** [comment]
Fairly sure that's been there since v1.x. Working with `HttpResponseMessage` is a decent workaround at the moment, but I think it would be nice to allow returning something with a bit more of a stripped down interface. I'll look at this when I next have some time.

**Comment by fonix232** [comment]
Good to know. It could be added to the documentation (no matter how small it is right now), so that others who want to work with received headers.

**Comment by auriou** [comment]
Does that has been implemented since?

 I would like get the header responses , how can we do?

**Comment by ahmedalejo** [comment]
@auriou one way is to set the return type of your call to ```Task<HttpResponseMessage>``` then you could dig out the headers you want.

**Comment by auriou** [comment]
Yes I used it to do on a single method.

But after I needed to recover the headers Rest at each call.

This is not very convenient and a lot of code has to be written.

To avoid this I have set up a specific HttpClientHandler to be notified of the change of headers.

here is my code.

One Test
`
[TestMethod]
        public void HeaderSimpleTest()
        {
            var headers = new Dictionary<string, string>();
            var ServerUrl = "http://localhost:26687/Service1.svc";
            var handler = new HttpClientHeaderHandler
            {
                UpdateHeaders = dictionary => { headers = dictionary; }
            };

            var client = new HttpClient(handler) { BaseAddress = new Uri(ServerUrl) };
            var restService = RestService.For<IService>(client);
            var resultBonjour = restService.Bonjour().Result;
        }
`

My Handler
`
public class HttpClientHeaderHandler : HttpClientHandler
    {
        public Action<Dictionary<string, string>> UpdateHeaders { get; set; }
       
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var res = base.SendAsync(request, cancellationToken);
            var autre = res.Result;
            if (UpdateHeaders != null)
            {
                var headers = autre.Headers.ToDictionary(p => p.Key, p => string.Join(";", p.Value));
                UpdateHeaders(headers);
            }
            return res;
        }
    }
`

My interface

`
    public interface IService
    {
        [Post("/Bonjour")]
        Task<string> Bonjour();

        [Post("/Connexion")]
        Task<authentRequest> Connexion([Body] authentRequest request);
    }
`

**Comment by KarinBerg** [comment]
I'm also very interested in an easier way to access response headers.

**Comment by WilkaH** [comment]
I think I'd prefer just wrapping my response object in a Refit type, and have Refit do the usual magic for my object as well as include the header info in the Refit type. So something like

```
class RefitResponse<T>
{
	public HttpResponseHeaders Headers { get; set; }
	public HttpStatusCode StatusCode { get; set; }
	// ... whatever else ...  
	public T Content { get; set;}
}

```
Then you could have something like this in your Refit interface:

```
[Post("/some/asyncapi/{someId}")]
Task<RefitResponse<SomeResponse>> SomeAsyncRemoteApiCall(int someId);
```

and then you can access the header info via `Task.Result.Headers["blah]"`

**Comment by nbsoftware** [comment]
Any news on this issue?
My use case is simpler than that: I want to be able to distinguish a `200 OK` from a `201 Created` of a `PUT` request... and still let Refit do its magic stuff on my objects.
I've searched throughout all issues and didn't find any relevant info apart from this thread.
Any other solution than using ```Task<HttpResponseMessage>```which will bypass all Refit magic?
Thanks

**Comment by onovotny** [comment]
Fixed in #414

**Comment by oatsoda** [comment]
An update to the documentation on how to use the `ApiResponse<T>` would be really useful as it took me a lot of searching to find this :)

**Comment by streamtree** [comment]
What's the current status of this? I have paging information being return in the response header that I need access to.
