### ISSUE TITLE
DefaultUrlParameterFormatter uses culture specific ToString

### ISSUE THREAD

**Issue by ncruces** [paulcbetts/refit#230]
[`DefaultUrlParameterFormatter`](https://github.com/paulcbetts/refit/blob/master/Refit/RefitSettings.cs#L27) uses the culture specific `ToString` method to convert parameters. When using Refit with certain cultures (e.g. in a mobile app), even a `double` will be serialized inconsistently (e.g. with a comma instead of a period). In general, it's bad form to use `ToString` for "serialization". Culture specific `ToString` is particularly bad.

This has bit me enough times, that I now use a [custom](https://gist.github.com/ncruces/be5a008f4ea49b22c6de479b52e61b4f) `IUrlParameterFormatter` every single time.

Does it ever make sense for this to be culture dependent?
Would it make sense to change the default (possibly breaking Refit for those who depend on it)?
Otherwise, maybe adding something like my [`InvariantUrlParameterFormatter`](https://gist.github.com/ncruces/be5a008f4ea49b22c6de479b52e61b4f) to Refit would be helpful.

I can setup a PR for any of the above, but would like some feedback before proceeding.

**Comment by mattiasnordqvist** [comment]
https://github.com/paulcbetts/refit/pull/66
?

**Comment by ncruces** [comment]
Yes, that's how `IUrlParameterFormatter` got added to Refit. And it's great that it exists, because that's what allows me to fix this on my own. Here, I'm wondering whether the **default** should be to call the culture specific `ToString`, and/or whether we should provide a utility class to help with this.

I mean, it may very well be too late to change the default, but what REST API depends on being invoked with the culture specific formatting of `float`/`double`/`decimal`?

The default *right now* is it use a comma (not a period) as the decimal separator in cultures such as spanish, portuguese, russian, german, french, italian, romanian, dutch, just to name a few. That's millions of people/devices/etc. Does this *ever* make sense for the query parameters of an API?

I regularly use Refit on mobile devices to invoke REST APIs that include location searches (latitude, longitude) and this bites me every single time, when it lands on a foreign device configured with a different culture. How many of you are/were aware of this?

**Comment by tehZeno** [comment]
Agreed. Has bitten me a couple of times over. In my opinion it would never make sense. 
Then again, formatting things like DateTime would be better in iso8601 instead of the culture invariant approach. It's good we can implement it ourselves though.

**Comment by jzeferino** [comment]
@ncruces thumbs up for the converter. And yes the conversion should be CultureInvariant. +1.

**Comment by ncruces** [comment]
@tehZeno I agree regarding ISO 8601, but at least the behavior is consistent, and you realize there's a problem before you ship.

Making this depend on the device's culture increases the probability that you're testing in a en-US device and never notice a problem before it lands in a differently configured device.

**Comment by onovotny** [comment]
I'm okay with making this a breaking change for v4.0

**Comment by onovotny** [comment]
This is fixed in 4.1 and invariant is now the default.
