### ISSUE TITLE
Please add PATCH as HTTP command

### ISSUE THREAD

**Issue by escamoteur** [paulcbetts/refit#232]
Hi,

I was wondering why PATCH is not supported according to your docs. My REST API uses PATCH as it describes what happens better then POST or PUT

Cheers
Thomas

**Comment by bennor** [comment]
Would you just expect it to work the same way as POST or PUT from Refit's point of view?

**Comment by bennor** [comment]
Sorry. It isn't mentioned in the docs, but PATCH is supported. Just try using `[Patch("/some/resource")]` the way you'd use any other attribute.

**Comment by escamoteur** [comment]
That's great. Thanks
