### ISSUE TITLE
Still maintaining

### ISSUE THREAD

**Issue by tofutim** [paulcbetts/refit#245]
Hi Paul, just curious to hear your plans for refit. Cheers, -Tim

**Comment by dumbguy5689** [comment]
I would be curious to know about this as well.

**Comment by onovotny** [comment]
We are very much maintaining this library, accepting PRs, fixing things and putting out releases as needed. Is there something in particular you're interested in?

**Comment by mosa99** [comment]
No, nothing particular, just curious that this was still being looked after.  

Thanks for all the hard work and for getting back to us. :)
