### ISSUE TITLE
aliasas when posting Json

### ISSUE THREAD

**Issue by tofutim** [paulcbetts/refit#246]
Hi, if I choose Json instead of urlencoded, my AliasAs does not pick up. In my class, I have upper case words, like "From". The Json should have my [AliasAs("from")] lower case version but it doesn't.

**Comment by C2H6O** [comment]
Having the same issue. It would be nice if AliasAs also applied to POST requests.

**Comment by bennor** [comment]
Use JSON.NET's `[JsonProperty("from")]` for request bodies.
