### ISSUE TITLE
Refit Meeting Minutes - 8th of July 2016 

### ISSUE THREAD

**Issue by ghuntley** [paulcbetts/refit#248]
# In attendance
- Paul Betts
- Brendan Forster
- Kent Boogart
- Oren Novotny
- Geoffrey Huntley
- Dennis Daume
- Michael Stonis

# With Apologies
- Paul Betts, as we bait and switched him with the promise of a social occasion with beer.

# The Plan

## SemVer
* Oren proposed that we adopt the .NET SemVer guidelines and there were no objections. We will move forward and adopt https://docs.microsoft.com/en-us/dotnet/articles/core/versions/index#semantic-versioning for ReactiveUI and all sister projects. - https://github.com/reactiveui/ReactiveUI/issues/1134

## Refit
* The major number will be bumped in the next release (needed because of netstandard)
* The continuous integration pipeline will be lifted from ReactiveUI and brought across to the Refit project. - https://github.com/paulcbetts/refit/issues/249
* Netstandard will be adopted - https://github.com/paulcbetts/refit/issues/235

**Comment by jerrywiltse** [comment]
+1 For Netstandard adoption. Thanks for your contributions.

**Comment by refactorthis** [comment]
Thanks guys - appreciate the fast work porting to core.

**Comment by ghuntley** [comment]
@refactorthis thank-you, for the thankyou. <3
