### ISSUE TITLE
How to handle the exceptions.

### ISSUE THREAD

**Issue by mrjbcs0811** [paulcbetts/refit#253]
How to handle the exceptions using refit in UWP10?

like Response status code does not indicate success: 401 (Unauthorized) directly goes to catch block.
which can have a callback if we want to do something.

How to get the whole HttpResponseMessage object not only the result.

**Comment by flagbug** [comment]
catch the `ApiException` that is thrown, there you'll have properties for the status code and friends

**Comment by ahmedalejo** [comment]
it´s kind of strange how often this question is asked is there a problem
with the clarity of the documentaion

https://github.com/paulcbetts/refit#user-content-retrieving-the-response

[Get("/users/{user}")]
Task<HttpResponseMessage> GetUser(string user);

**Comment by ahmedalejo** [comment]
May be we should make this clearer. But how?

**Comment by KarinBerg** [comment]
A question to HttpResponseMessage: If I use the HttpResponseMessage as return type, then I have to do all the status code handling and the deserialization of the JSON content by myself, right? Refit doesn't offer some handy methods for this?

**Comment by bennor** [comment]
@KarinBerg Yes - if your interface method returns `Task<HttpResponseMessage>` then all the decoding of it is up to you.

If you catch `ApiException`, there's a `GetContentAs<T>()` method you can use to deserialize a JSON error response.
