### ISSUE TITLE
Nuget 3.0 Regression  cannot install for PCL Profile 7

### ISSUE THREAD

**Issue by kjeremy** [paulcbetts/refit#257]
In attempting to upgrade refit from 2.4.1 to 3.0 I am getting the following error:

> Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by onovotny** [comment]
Unfortunately this is a bug in the `Sys.Runtime.InteropServices.RuntimeInformation` package: https://github.com/dotnet/corefx/issues/10445. when trying to install into a "netstandard 1.1" profile-based PCL (like 7 or 111).

The workaround for now is to use `project.json` and a `netstandard1.1` library. Any project type can use .net standard.

**Comment by joaoasilva** [comment]
I'm using Xamarin and I'm trying to install refit on my Portable project, can anyone explain how can I fix this? How do I use project.json and netstandard1.1 if I'm using mono?
Thanks

**Comment by ahmedalejo** [comment]
I'd recommend using version 2.0.0+ there are some issues with v3.0.0

**Comment by onovotny** [comment]
I don't think supports .NET Standard yet, but I believe they're working on it. Xamarin Studio just got support for it in the stable branch on Tuesday.

**Comment by rranjithkumar100** [comment]
3+ version not installed.. but 2.4 refit installed successfully.

Shall I use this lower version?

**Comment by onovotny** [comment]
XS supports .NET Standard Libraries. There may be a bug with the NETStandard.Library 1.6.0 which is resolved by installing NETStandard 1.6.1 first.

**Comment by onovotny** [comment]
Will be fixed in 3.1
