### ISSUE TITLE
Install Refit on Xamarin Forms PCL Error

### ISSUE THREAD

**Issue by LuigiMaestrelli** [paulcbetts/refit#260]
I'm trying to install the 3.0 version on my Xamarin.Forms PCL Application.
In the platform specifics projects the package installs with no problem.
But on the Portable project I got this error:

> Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I was able to install the 2.4.1 version without any problems, but not the 3.0.

My portable project targets:

* .NET 4.5
* ASP.NET Core 1.0
* Windows 8
* Windows Phone 8.1
* Xamarin.Android
* Xamarin.iOS
* Xamarin.iOS (Classic)

**Comment by onovotny** [comment]
Closing as a dup or https://github.com/paulcbetts/refit/issues/257. The workaround is to use `project.json` instead of `packages.config` in your project. My [blog](https://oren.codes/2016/07/09/using-xamarin-forms-with-net-standard/) shows how to use Xamarin Forms with `project.json` and .NET Standard.

**Comment by kjeremy** [comment]
Isn't Microsoft dumping `project.json`? https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/

**Comment by biapar** [comment]
Is't enough to install refit via nuget and reference .netstandard lib into PLC project?
