### ISSUE TITLE
Parameter name: replacement cannot be null exception when using Refit with ModernHttpClient on Nexus5X

### ISSUE THREAD

**Issue by mikescandy** [paulcbetts/refit#261]
I stumbled on a fairly specific issue. As in the description, my app uses Refit and ModernHttpClient.
The test involved using a request like this:

> [Post("/api/blah?param1={param1}&param2={param2}")]
> Task<SomeDto> DoSomething(string param1, string param2);
> and sending as parameters a blank space
> On a Samsung S5 Neo (android 5), on multiple Genymotion emulators with different android version everything works fine.
> On a Nexus5X I get an exception with the attached stacktrace.
> [stacktrace.txt](https://github.com/paulcbetts/refit/files/472125/stacktrace.txt)

Switching to the .Net httphandler or trimming the spaces prevents the exception.

**Comment by ahmedalejo** [comment]
Two things you need to verify:

1. Change your api contract definition to
```csharp
[Post("/api/blah")]
Task DoSomething(string param1, string param2);
```

2. And most important Ensure that your `AuthenticatedHttpClientHandler` is being used and that it isn´t mangling urls(wrongly) or interfering with `ModernHttpClient`

**Comment by onovotny** [comment]
Using `ModernHttpClient` isn't supported anymore due to its many known issues.
