### ISSUE TITLE
Refit library ignores base url's get parameters 

### ISSUE THREAD

**Issue by Revenge94** [paulcbetts/refit#262]
Hi I define a base url which finish with : "index.php?route=mobile" . The path of webservice functions start after this url . But Refit library ignore part "?route=" .  How can I handle this? Should I add "route " parameter to all webservice functions . It is not best practice.

I'm using version 2.4.1 of refit.

**Comment by Revenge94** [comment]
Maybe not define service path (index.php?route=) in base path is better.

**Comment by ahmedalejo** [comment]
- You could always add a query string `route=mobile` to your Url via a delegating handler
- Or use an **header** for specifying the `route` via `HttpClient.DefaultRequestHeaders.Add("route", "mobile")` that you pass to **Refit**
