### ISSUE TITLE
How to set timeout time in refit

### ISSUE THREAD

**Issue by receme** [paulcbetts/refit#264]
Is there a way to set a timeout time in refit call. Or is there a default time already set?

**Comment by ahmedalejo** [comment]
You could just give to **Refit** a ``HttpClient` with a configured `Timeout` property.

or 

just pass a `CancelationToken` as the last parameter of your interface method. This would handled cancelling requests before timeout does.

**Comment by receme** [comment]
Thanks, I have done it like this.

```
HttpClient httpClient = new HttpClient ();
httpClient.BaseAddress = new Uri (url);
httpClient.Timeout = new TimeSpan (0, 0, 30);
api = RestService.For<ILambdaAuth> (httpClient);
```
