### ISSUE TITLE
How to  switch host URL at runtime?

### ISSUE THREAD

**Issue by opcodewriter** [paulcbetts/refit#266]
How to change the host URL at runtime?
The only option I see is basically recreate the API service instance:

`RestService.For<IMyApi>()`

The issue with this this is supposed to be an dependency injected singleton.... 
There might be instances of which already have the IMyApi instance...

**Comment by ahmedalejo** [comment]
Then inject a singleton factory

**Comment by ahmedalejo** [comment]
Note that this isn´t a **Refit** limitation, .NET´s `HttpClient` doesn´t
allow changing the BaseAddress after the first request made with that
instance

A workarround is to use a `DelegatingHandler` that mangles the *RequestUri*
of the Snippet HttpRequestMessage

**Comment by opcodewriter** [comment]
> .NET´s `HttpClient` doesn´t
> allow changing the BaseAddress after the first request made with that
> instance
> 

Yeah, of course, it makes sense.
Thanks @ahmedalejo !

**Comment by opcodewriter** [comment]
Thanks again @ahmedalejo 
Any other ways to achieve this other than using DelegatingHandler`?
What if Refit had a way to provide a `HttpClient` instance, like a factory or something?

**Comment by opcodewriter** [comment]
`BaseAddress` can be set on a `HttpClient` instance. But the issue is that I can't get the `HttpClient` instance from the object generated from `RestService.For<IApi>(httpClient)`

**Comment by onovotny** [comment]
If you add a get property of type `HttpClient` named `Client` on your `IApi` it should expose it to you.

**Comment by opcodewriter** [comment]
@onovotny Wow, thanks! Can you please share some thoughts about how does that magic works?
How does Refit know how to populate that property?
I don't see it mentioned in the documentation.

**Comment by onovotny** [comment]
It's not magic, it's just set on the instance by the generated code....but unless your interface exposes it, you'll never see it.

**Comment by nareshpatel** [comment]
It is possible to make calls to endpoints with different baseurls via SendAsync method from HttpClient via providing Uri via HttpRequestMessage.

**Comment by yoav2** [comment]
There different answers here...so its not clear 
Can BaseAddress can be changed after static httpClient  was already run requests to a different URL?
