### ISSUE TITLE
How to Handle Errors

### ISSUE THREAD

**Issue by frostymarvelous** [paulcbetts/refit#270]
I don't see anything concerning error handling.
How is this done?

Thanks

**Comment by Cheesebaron** [comment]
You get a RefitException which should give you enough information about what went wrong. Catch that and handle errors.

**Comment by MisterHux** [comment]
Isn't it actually `ApiException`?  And then you can pull error content out using `ApiException.GetContentAs<T>()`

**Comment by ahmedalejo** [comment]
@frostymarvelous please take a look at the following issues:

- #198 Handle 500 internal server error
- #231 Disable Refit from hiding HTTP content in case response code wasn't 200 (ApiException)
- #240 QUESTION Exception Handling
- #253 How to handle the exceptions.
- #258 How to enable logging?

**Comment by frostymarvelous** [comment]
Thanks so much guys. You've been very helpful.
