### ISSUE TITLE
RefitStubs.g.cs missing when using xbuild

### ISSUE THREAD

**Issue by dageforce** [paulcbetts/refit#276]
Hi,

Not sure if it it's Refit me or xbuild.
I am targeting Refit 3.0.1 using Nuget 3 (project.json file) in a PCL library.

```
{
  "dependencies": {
    "NETStandard.Library": "1.6.0",
    "refit": "3.0.1"
  },
  "frameworks": {
    "netstandard1.4": {}
  },
  "supports": {}
}
```

When I build my project via Xamarin Studio, the files are generated correctly, however when I build the project via xbuild (either pointing to the csproj or sln file) it does not generate any of the RefitStub files. I then get a "doesn't look like a Refit interface" error during runtime.

Any advice would be greatly appreciated.

**Comment by onovotny** [comment]
Seems like it's not including the generated file

**Comment by onovotny** [comment]
Closing this out. project.json is no longer supported. Please try the latest version.
