### ISSUE TITLE
Support iOS 32 bits

### ISSUE THREAD

**Issue by joseprl89** [paulcbetts/refit#279]
I understand it's a somewhat deprecated platform, but we'd be interested in using Refit in projects that have to support iOS 32 bits.

Is this something achievable? What needs to happen for this to work? If we were to file a PR for it, would you accept it?

**Comment by ahmedalejo** [comment]
@joseprl89 Isn´t currently support? could you enlighten us how/where you got to this conclusion(not supporting iOS 32 bits)

Good PRs has always been accepted, you can check the pull request history.

Cheers

**Comment by joseprl89** [comment]
It's like the first bit of the readme:

> The following platforms are not supported:
> Xamarin.iOS 32-bit - build system doesn't support targets files

I was looking through the codebase and am unsure on what needs to be done to add support, since I am just now starting to learn C#, so some directions would help me if I am to do it.

**Comment by ahmedalejo** [comment]
@joseprl89 that might be outdated(the doc aren´t updated as fast as features are added), have you simply tried using it and didn´t work?

**Comment by joseprl89** [comment]
I didn't test it since I saw that and looked into the issues for a reference to iOS32 bits and found #122 with a mention that it is not supported (+ documentation).

If it is supported, could you guys update the Readme file?

**Comment by ahmedalejo** [comment]
The "Xamarin.Forms support" refere to Xamarin.Form integration and it´s about 2 years ago. Xamarin.Forms it is supported fully, and i have an iOS in the Apple Store using Xamarin.Forms and solely **Refit** for communicating with our webapi server. It worked on Windows phone and UWP as well.
Moving one..

> If it is supported, could you guys update the Readme file?

**You guys** includes you too you know?. If you tested it on that platform and it works then you could suggest a document update.

What **Not Supported** in theory really means is that, *"whether it runs or not, we currently do not have enough people interested in this support, so we currently can´t pledge voluntary support/maintainance for that platform"*

Just try it out by installing it in the iOS project and any referenced project that you intend to use it in,
Give feedback and we can progress from that.

Cheers

**Comment by onovotny** [comment]
I'm afraid iOS 32 bit will never be supported. Not only does it not support proper build targets, but there's no other support for it within the Xamarin ecosystem anymore either.

**Comment by ahmedalejo** [comment]
never say never @onovotny 😄

**Comment by joseprl89** [comment]
Just verified, it works on an iPhone 5 (32 bits) running iOS8 using 2.4.X due to #257 in case someone stumbles upon this ticket.

I think that soon enough we'll be able to drop suport on iOS32 bits since those are rather old school devices.

Cheers!
