### ISSUE TITLE
Error when calling method on UWP & Windows Phone 8.1

### ISSUE THREAD

**Issue by tribalboy** [paulcbetts/refit#280]
Hi Guys,

  I have a Xamarin Forms prject which works fine on Android & iOS when using Refit 2.4.1 but I am getting errors when trying to use the same on UWP & WinPhone 8.1.

I get the below error on UWP
`  The API 'System.Array.get_LongLength()' cannot be used on the current platform. See http://go.microsoft.com/fwlink/?LinkId=248273 for more information.`

& the one below on Windows Phone 8.1
`The API 'System.Array.get_SyncRoot()' cannot be used on the current platform. See http://go.microsoft.com/fwlink/?LinkId=248273 for more information.`

I have tried with the platform types x86, x64 & AnyCPU but the result is the same. The output from the debug window shows InvalidOperationException & the last assemblies loaded are the Serialization ones. 

```
..\System.Net.Primitives.dll'. Module was built without symbols.
..\System.Runtime.Serialization.Primitives.dll'. Module was built without symbols.

Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
```

This leads me to assume that Refit is having problems with Serialization. Can someone help me out as to how I can get round this.

Many Thanks

**Comment by onovotny** [comment]
@tribalboy Can you try Refit `3.0.1`? `2.4.1` is very old and likely has issues with UWP.

**Comment by tribalboy** [comment]
Hi @onovotny , thanks for the reply. I tried with 3.0.1 for UWP to no avail. I get the same issue

**Comment by onovotny** [comment]
Do you have a stack trace?

**Comment by tribalboy** [comment]
Sorry I should have included that earlier

```
{"The API 'System.Array.get_LongLength()' cannot be used on the current platform. See http://go.microsoft.com/fwlink/?LinkId=248273 for more information."}

 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Refit.FormValueDictionary..ctor(Object source)
   at Refit.RequestBuilderImplementation.<>c__DisplayClass6_0.<buildRequestFactoryForMethod>b__0(Object[] paramList)
   at Refit.RequestBuilderImplementation.<>c__DisplayClass12_0`1.```
<<buildCancellableTaskFuncForMethod>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Service.<Login>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at  PageModel.<OnRegister>d__15.MoveNext()

```

**Comment by onovotny** [comment]
Also, any kind of minimal repro?

**Comment by onovotny** [comment]
Are you trying to pass an array directly as a parameter into something?

I'm guessing that https://github.com/onovotny/refit/blob/a83949533f8a4f981264f5099c92406555ad7d5f/Refit/RequestBuilderImplementation.cs#L755 doesn't work with UWP/Wpa81 correctly as reflection is turning up types that aren't actually available at runtime.

**Comment by tribalboy** [comment]
Yes I am trying to do the following

`api.PostLogin(authorisationHeader, Encoding.UTF8.GetBytes("XXX"));`

Its supposed to return a string value

**Comment by onovotny** [comment]
Given the current way the code uses reflection, you won't be able to directly post an array as a UrlEncoded body.

If that's what you need to do, then I'd suggest making it a string parameter, putting the Body attribute on it and doing your own encoding of what you want from the array. Reflection does not appear to be stripping out the not supported members currently.

**Comment by tribalboy** [comment]
Thanks a lot @onovotny, I am now passing a string and it seems to go through fine
