### ISSUE TITLE
Could not load file or assembly 'Refit, Version=3.0.1.0

### ISSUE THREAD

**Issue by chamamo** [paulcbetts/refit#285]
Hi,

I'm trying to use the library on UWP (Win10).

The package is installed correctly but when I execute I have thir error:

Exception thrown: 'System.IO.FileLoadException' in mscorlib.ni.dll

Additional information: Could not load file or assembly 'Refit, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Thank you in advance.

**Comment by onovotny** [comment]
Please try again with 3.1 and re-open if still an issue
