### ISSUE TITLE
dotnet core 1.1 build exception

### ISSUE THREAD

**Issue by lasrol** [paulcbetts/refit#292]
We have a dotnet core 1.1 project running on csproj using visual studio 2017 RC. 

If we run `dotnet build` we get an exception where the system cant find the **RefitParams.rsp**, i checked the obj folder and as the exception states the files is not there. 

When we are building and running using VS 2017, the **RefitParams.rsp** gets generated and the solution builds. When we run `dotnet build` the files seems to be deleted and not regenerated. 

Any toughts on why this happens?

Error:

> C:\UserProfile\.nuget\packages\refit\3.0.1\build\netstandard1.3\refit.targets(33,5): error MSB3073: The command ""C:\UserProfile\.nuget\packages\refit\3.0.1\build\netstandard1.3\..\..\tools\InterfaceStubGenerator.exe" "obj\Release\netstandard1.3\\RefitStubs.g.cs" "PATH_TO_PROJECT_CONTAINING_CSPROJ" "obj\Release\netstandard1.3\\RefitParams.rsp"" exited with code -532462766.

**Comment by onovotny** [comment]
Needs to be investigated, but for now you can use `msbuild /t:build` or `/msbuild /t:pack` to use the desktop msbuild instead of `dotnet build` or `dotnet pack`. That should work.

**Comment by lasrol** [comment]
Using msbuild worked 👍 I was also using the 1.0.0-preview4-004233 SDK for dotnet core. It seems updating to 1.0.0-rc3-004530 also resolved the issue and `dotnet build` is working.
