### ISSUE TITLE
ApiException.Content is always null when a response type is defined.

### ISSUE THREAD

**Issue by gabrielsadaka** [paulcbetts/refit#293]
`ApiException.Content` is always null when calling an endpoint that returns a `Task<Response>` but works fine when the endpoint has no return type i.e. `Task`.

This is my API Interface:

```
public interface IUserApi
{
	[Post("/api/user")]
	Task<CreateUserResponse> CreateUser([Body] CreateUserRequest request);

	[Post("/api/user/{userId}/_change-email")]
	Task ChangeEmail(Guid userId, [Body] ChangeEmailRequest request);
}
```

This is my error response class:

```
public class ErrorResponse
{
    public string[] Errors { get;set; }
}
```

This is how I am calling the API:

```
try
{
    var createUserResponse = api.CreateUser(user);
}
catch(ApiException ex)
{
   var error = ex.GetContentAs<ErrorResponse>();
   // error is null
}
```

`ApiException.Content` has the correct content when I call `IUserApi.ChangeEmail` however when I call `IUserApi.CreateUser` it is always null even though the server is returning content.

I have traced it down to this line here https://github.com/paulcbetts/refit/blob/8e602ef25aedf3d38b4dddf0bd9d9fbb7d2f82bf/Refit/RequestBuilderImplementation.cs#L357. Because `HttpCompletionOption.ResponseHeadersRead` is passed to `SendAsync` the content is not read by the time the `ApiException.Create` method checks if it is null https://github.com/paulcbetts/refit/blob/master/Refit/RestService.cs#L112 so it is never read. Removing the `HttpCompletionOption.ResponseHeadersRead` parameter resolves the issue however that would break any code that tries to use the cancellation token to prematurely stop the request. 

I unfortunately do not have anymore time to investigate the issue at the moment, I may be able to find some time in the coming days or if someone else has a good fix for it that would be great.

**Comment by MrThreepwood** [comment]
Did you ever find a way around this or end up working on it?

**Comment by gabrielsadaka** [comment]
Unfortunately not, I did not have enough time to look into it further at the time so we gave up on using Refit and went back to our original RestSharp implementation and I have not found another use for Refit since then. I might look into it again soon if I find time.

**Comment by onovotny** [comment]
I can't repro this in the test I created in this commit: https://github.com/paulcbetts/refit/commit/84f46c6e1d2b75f01da12df349f9adb30f7a6d5a

Closing for now but will reopen if we can get a repro.
