### ISSUE TITLE
... doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.

### ISSUE THREAD

**Issue by zunama** [paulcbetts/refit#295]
I am trying to do a simple demo of refit with a live endpoint but below is what I have and I get the above error. This is in an .Net Core project based on std 1.6. Any thoughts. This is simply the demo code and it's a no go.

```
using System.Threading.Tasks;
using Refit;

public interface IWebServiceCall
 {
     [Get("/simple/doing/this")]
     Task<Response> GetSomething();
}

// in main
var client = RestService.For<IWebServiceCall>("https://api.this.com");
```

**Comment by darach** [comment]
Having the same issue with a similar snippet in VS2015 / net45 / Refit 3.0.1.

Have tried using referenced assemblies via Nuget and built from source.

Interestingly, the same snippet packaged as a unit test and hacked into the refit tests
works just fine, so this seems like some kind of configuration step or dependency is
required and/or a code generation / loading issue.

Also, the packaged IGitHubApi copied into a new solution also manifests the same
issue. The fix may be obvious to a full-time .NET/csharp developer but is not obvious
for those of us who aren't such as myself.

**Comment by darach** [comment]
Turns out this was a stale reference to a prior version of refit downloaded via nuget.
Removing and re-adding the correct 3.0.1 assembly resolved the codegen issues.
