### ISSUE TITLE
Cannot encoding string parameter with '&' correctly.

### ISSUE THREAD

**Issue by shaopengz** [paulcbetts/refit#298]
Tring to create a function with

` 
[Get("/api/cases/statistics/{countyId}/{judgeId}/{reliefSought}/DecisionTimeByReleifSought")]
Task<JudgeReliefSought5NumberSummary> GetJudgeReliefSought5NumberSummary(string countyId, string judgeId, string reliefSought);
`

However, when I set 
`var reliefSought = 'JUDGMENT OF FORECLOSURE & SALE'` with `&` inside.

The function cannot encoding this correctly and request the right url.

**Comment by dotnetchris** [comment]
I'm not really sure that refit should do anything about this, you can always encode the fragment yourself if you want to pass refit invalid url text.

**Comment by onovotny** [comment]
values passed in should be UrlEncoded if used on the path/query string. Will look closer.
