### ISSUE TITLE
Works on Mono?

### ISSUE THREAD

**Issue by Daniel15** [paulcbetts/refit#30]
I'm wondering whether Refit works on Mono on Linux? The readme mentions Xamarin.Mac but I don't know whether this is the same as the open-source Mono.

**Comment by aflorenzan** [comment]
Now, almost a year ago, Refit works on Xamarin Studio without any problem which is the "new Mono Develop" and use Mono Framework as Foundation. @Daniel15 Can we close this issue?

**Comment by Daniel15** [comment]
Should Mono be added to the "Where does this work?" in the readme then? It's not mentioned there.
