### ISSUE TITLE
Abbreviated import paths not properly managed by Refit

### ISSUE THREAD

**Issue by imagineblueeyes** [paulcbetts/refit#301]
Maybe it's a curse, but Resharper helps us to remove unnecessary language from source files.  So in my current Interface, the paths start out at full length, including prefixes:

```cs
namespace myNamespace
{
	using System.Threading.Tasks;
	using myNamespace.APIResponses;
	using Refit;
```

... but then Resharper grays out the unneeded prefixes -- the redundant parts that the namespace already declares for us. So I remove them out of neatness:

```cs
namespace myNamespace
{
	using System.Threading.Tasks;
	using APIResponses;
	using Refit;
```

This compiles perfectly and gets me a green light on Resharper.

Refit does not handle this situation very well.  It spits out the exact import as declared rather than the full path, as required.  So the auto-generated .g.cs file looks like this:

```cs
﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using APIResponses;
using Refit;
```

The line:

```cs
using APIResponses;
```

is illegal -- it lacks its myNamespace prefix.  So the app fails to compile.

Please consider integrated/merging the namespace into your paths for all imports so those paths are complete and legal.

Stephen Marcus

**Comment by Cheesebaron** [comment]
> Please consider integrated/merging the namespace into your paths for all imports so those paths are complete and legal.

Please consider not using f'ed up styles in your code (I know this is very much personal preference), which make it unclear what type you are using and what namespace it comes from.

Put a ReSharper rule around it to ignore it.

**Comment by paulcbetts** [comment]
Lol, I'll leave the style bit up to the crowd to judge, but I do agree that Resharper trying to mess with generated code is probably Incorrect, you should get Resharper to ignore this file
