### ISSUE TITLE
Simplest way to get full HTTP request/response corresponding to specific API call

### ISSUE THREAD

**Issue by alexsorokoletov** [paulcbetts/refit#302]
I'm calling REST api using Refit (I love it!  👍 ).
Now, for auditing/security reasons I need to get complete HTTP request/response (or body at least) corresponding to my API call that I just made.

What would be simplest way and what would be correct way to do that? (I hope simple=correct).
I've seen this issue about logging (#258), not sure how to apply this to my problem.

Thank you

**Comment by Cheesebaron** [comment]
Do you just want to pint it out, or do you want the object?

**Comment by alexsorokoletov** [comment]
I need a string/stream of HTTP request/response in order to log it to my system for auditing purposes.

**Comment by Cheesebaron** [comment]
Change the return type to `HttpResponse` and do the deserializing of the object yourself. This way you can get headers, body etc. as needed.

**Comment by alexsorokoletov** [comment]
Thank you, @Cheesebaron, I did not know it is possible.

In this case I would just use HttpClient and that's it. No point using Refit this way.

**Comment by bennor** [comment]
@alexsorokoletov You can get all the benefits of Refit and still get access to the raw request/response objects using a `DelegatingHandler`. See #258 for an example.

**Comment by bennor** [comment]
Sorry. Just noticed you referenced that. 

Once you've created a delegating handler, you wire it up using the first code block in this message: https://github.com/paulcbetts/refit/issues/258#issuecomment-243394076
