### ISSUE TITLE
JsonSerializerSetting for TypeNameHandling not working

### ISSUE THREAD

**Issue by cfl777** [paulcbetts/refit#303]
Hi,
Been struggling to get my deserialization working - we are using polymorphism. 

I get the following error:
**Type is an interface or abstract class and cannot be instantiated**

I tried to set the settings for refit, which should make it work - works for other examples:
[http://stackoverflow.com/questions/5780888/casting-interfaces-for-deserialization-in-json-net](url)

    
        `
        var JourneyClient = new HttpClient(messageHandler)
        {
             BaseAddress = uri
        };
```

       `
return RestService.For<IJourneyServiceClient>(JourneyClient, new RefitSettings
	{
		JsonSerializerSettings = new JsonSerializerSettings
		{
			TypeNameHandling = TypeNameHandling.Auto
		}
	});
```

Anything I'm missing? Please assist this is causing a massive deadlock in our teams development

**Comment by Cheesebaron** [comment]
Is this a Refit issue? Refit just uses Newtonsoft.Json, so if you can use that to deserialize your payload, you can use Refit too.

**Comment by cfl777** [comment]
@Cheesebaron thank you for reply. 
I assumed it was a refit issue because it didn't seem to change anything when setting the `TypeNameHandling`. 
We found a possible side route to use - busy testing

**Comment by swapnil591** [comment]
Check below code

Rest.For<ITestApi>(client, new RefitSettings
            {
                ContentSerializer = new JsonContentSerializer( 
                    new JsonSerializerSettings
                    {
                        NullValueHandling = NullValueHandling.Ignore
                    }
                )
            });
