### ISSUE TITLE
refit.targets generates incorrect file name on linux w/ dotnetcore build chain

### ISSUE THREAD

**Issue by Tanhe** [paulcbetts/refit#311]
`<PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
      <RefitExecCmd>mono "$(MSBuildThisFileDirectory)../../tools/InterfaceStubGenerator.exe" "$(IntermediateOutputPath)\RefitStubs.g.cs" "$(MSBuildProjectDirectory)" "$(RefitParameterFile)"</RefitExecCmd>
    </PropertyGroup>`

Results in a file named `\RefitStubs.g.cs` in the intermediate output directory.

`<ItemGroup Condition="Exists('$(IntermediateOutputPath)\RefitStubs.g.cs')">
        <Compile Include="$(IntermediateOutputPath)\RefitStubs.g.cs" />
    </ItemGroup>`

Resolves to trying to include the file without the leading backslash as msbuild handles the \ vs / but the code in the InterfaceStubGenerator does not.

Net result is that the final compiled project doesn't have the autogenerated types in it.

**Comment by Tanhe** [comment]
Oh...this is already fixed in PR #307

**Comment by Tanhe** [comment]
Temporary fix. Add the following to your affected csproj:

` <Target Name="FixRefitStubOnLinux" Condition="'$(OS)' != 'Windows_NT'" AfterTargets="GenerateRefitStubs">
    <Message Text="FixRefitStubOnLinux: Moving '$(IntermediateOutputPath)\RefitStubs.g.cs' to '$(IntermediateOutputPath)/RefitStubs.g.cs'" />
    <Move SourceFiles="$(IntermediateOutputPath)%5CRefitStubs.g.cs" DestinationFiles="$(IntermediateOutputPath)/RefitStubs.g.cs" />
  </Target>`

**Comment by onovotny** [comment]
Just merged it
