### ISSUE TITLE
"doesn't look like a Refit interface" with Refit 3.1.0 + VS2015 on Windows in an ASP.Net Core Project

### ISSUE THREAD

**Issue by JelleDamen** [paulcbetts/refit#328]
I'm trying to use the Refit package within another webservice (asp.net core project) I'm not even sure if that is possible.

```
public interface IPushNotificationService
{
    [Refit.Post("/push/notifications")]
    Task<Result> SendPushnotification([Refit.Body]Notification notification);
}
```

Would like to know if this is possible. And if it is, why it's not working :( Thanks.

**Comment by onovotny** [comment]
Not really following -- you should be able to use it in any project type. Do you have a small repro?

**Comment by JelleDamen** [comment]
I can't send you the project I'm working on. I'll try to reproduce in a new small test project.

**Comment by JelleDamen** [comment]
I got the same error in this repro project: https://drive.google.com/open?id=0B4TyZ0A9eH_XdW1sR0VrcDJyMkE

It's the default webapi that is generated as a sample by Visual Studio (Web Api) I've created a call `/Values/test` that creates a Refit Rest Service Instance (that fails)

**Comment by bennor** [comment]
It's a bit of a weird quirk, but you need a `using Refit;` in the interface file.

**Comment by bennor** [comment]
But is dotnet core supported at all by 3.1.0?

**Comment by JelleDamen** [comment]
Too bad that did not work. :(

As you can see, i'm already specifying the Namespace in each statement/attribute:

```
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1
{
    public interface IPushNotificationService
    {
        [Refit.Post("/push/notifications")]
        Task<AzureResult> SendPushnotification([Refit.Body]AzureNotification notification);//, [Refit.Header("X-API-Token")] string token);
    }
}
```

Added `using Refit;` but with the same result.

**Comment by bennor** [comment]
The `using` is required, and you need to remove the `Refit.` before each attribute. i.e. `[Get("/foo")]` instead of `[Refit.Get("/foo")]`.

The reason for this is that we only do analysis on the syntax tree (for perf/simplicity reasons), so we check for a using statement that references Refit, and only check for attributes with the shorter names.

**Comment by bennor** [comment]
See `FindInterfacesToGenerate` and `HasRefitHttpMethodAttribute` in [InterfaceStubGenerator.cs](https://github.com/paulcbetts/refit/blob/master/InterfaceStubGenerator.Core/InterfaceStubGenerator.cs)

**Comment by JelleDamen** [comment]
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Refit;

namespace WebApplication1
{
    public interface IPushNotificationService
    {
        [Post("/push/notifications")]
        Task<AzureResult> SendPushnotification([Body]AzureNotification notification);
    }
}

```
I now have this, but still the same error pops up:

```
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=IPushNotificationService doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.
  Source=Refit
  StackTrace:
       at Refit.RestService.For[T](HttpClient client, RefitSettings settings)
       at WebApplication1.Controllers.ValuesController.Test() in C:\Users\Jelle\Documents\git\tempproject\WebApplication1\src\WebApplication1\Controllers\ValuesController.cs:line 15
       at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<>c__DisplayClass37_0.<WrapVoidAction>b__0(Object target, Object[] parameters)
       at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
  InnerException: 

```

**Comment by JelleDamen** [comment]
Maybe it has to do with this part of the error: `Make sure Refit is installed in the project.` What does 'installed' mean? I've added the package successfully.

**Comment by bennor** [comment]
You should only need to pull Refit in from NuGet. Perhaps the build task that runs the generator isn't running for some reason?

**Comment by onovotny** [comment]
A small isolated repro that mirrors the current setup would help.

**Comment by JelleDamen** [comment]
Here is the sample project with the same error https://drive.google.com/open?id=0B4TyZ0A9eH_XdW1sR0VrcDJyMkE

**Comment by onovotny** [comment]
Ok, this is easy -- refit does not work with project.json projects at all..you have to convert that over to csproj based. project.json isn't really supported by anything anymore.

**Comment by onovotny** [comment]
run `dotnet migrate` and it'll migrate it over.

**Comment by JelleDamen** [comment]
Yes, that was it! The project is not compatible with VS2015 anymore, but just installed VS2017 ;) Thanks for your help everyone!
