### ISSUE TITLE
UrlEncoded Body Serialization Aliasing

### ISSUE THREAD

**Issue by HelloKitty** [paulcbetts/refit#330]
Based on the source from: https://github.com/paulcbetts/refit/blob/master/Refit/FormValueDictionary.cs it appears that aliasing is supported however many people, including myself, will have annotated our models with JSON.NET. Since you already have JSON.NET as a dependency why not also include JsonProperty reflection to support the aliasing feature on models that are only annotated with JSON.NET attributes.

**Comment by bennor** [comment]
You mean use the `[JsonProperty(Name="Foo")]` attribute values if present? We could I guess, but it seems a bit counterintuitive, as they're not being used for JSON. 

It would cause problems in the (unlikely) case of someone using the same object to serialize to JSON and submit as a form but wanting different property aliases. I think that could be avoided by allowing the use of both and having `[AliasAs("foo")]` take precedence.

Thoughts @onovotny?

**Comment by HelloKitty** [comment]
Well due to the lack of configuration there isn't much else I can do other than request for a fallback. Alternatively extracting the attributes into a separate netstandard1.0 assembly may be beneficial to consumers of the library. I could likely annotate these models if I didn't need to fully depend on the entire Refit project in doing so.
