### ISSUE TITLE
Post requests turn out to be Get

### ISSUE THREAD

**Issue by balinabbb** [paulcbetts/refit#333]
Hi,
I can not make POST requests to my api for some reason. 
```csharp
using System.Net.Http;
using System.Threading.Tasks;
using Refit;

namespace MyProject.Api
{
    [Headers("Accept: application/json")]
    public interface IApiTemplate
    {
        [Post("/uuids")]
        Task<HttpResponseMessage> CreateUuid();
    }
}
```

The response is "Method GET not allowed". However if I change the Post Attribute to Put, or Delete the method will be Put or Delete (which are also not allowed). So the Post attribute only won't result in the expected http method.

I did try with some other methods, but the result is the same.

First I was using 3.1.0, later changed it to 2.4.1 which I used until now.
I have a PCL and a Xamarin.iOS project, both have the Refit 2.4.1 included. The api code is in the PCL.

Cheers,
Bálint

**Comment by balinabbb** [comment]
Ok, well I am sorry. Turns out the problem was, that the url should have been "/uuids/", and without the '/' at the end I got a redirect.

**Comment by bennor** [comment]
Glad you got it sorted. 😃
