### ISSUE TITLE
Shared/Global Query Parameter Values

### ISSUE THREAD

**Issue by adamfisher** [paulcbetts/refit#334]
Lets assume I have a service defined with two endpoints as shown below. How would I go about removing the api key parameter from all of the methods and allowing it to be globally added as a query parameter for both endpoints?

In other words, given multiple endpoints that all need to have the same query parameter value, how can you tell Refit about it such that the value does not need to be passed in to each endpoint method that requires it?

```csharp
public interface ISomeApi
{
	[Get("endpoint1")]
	object GetEndpoint1(string apiKey, string paramA);

	[Get("endpoint2")]
	object GetEndpoint2(string apiKey, string paramB);
}
```

**Comment by adamfisher** [comment]
Due to the lack of flexibility to hook into some event or a way to always add specific query parameters without having to explicitly specify them in every method, I have decided to stay with RestSharp. Might be useful on the mobile side though.

**Comment by onovotny** [comment]
You could do that with a custom HttpClientHandler that always adds a parameter to the request. If you look at how AuthenticatedHttpClientHandler adds the auth header, it would be similar. HttpClientHandlers can be nested too so you can stack them together.
