### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by CraigMellon** [paulcbetts/refit#335]
Do you have any examples of Injecting a service into a controller using aspnet core DI.

Currently in my controllers constructor I'm creating rest client with RestService.For<Interface>, is it possible to inject this in the constructor parameters so I can mock the rest service for testing?

**Comment by ahmedalejo** [comment]
@CraigMellon the following should do what you want:
```csharp
public class Startup  
{
    public void ConfigureServices(IServiceCollection services)
    {
        ...
        services.AddTransient(_ => RestService.For<ICraigMellonGitHubApi>("https://github.com/CraigMellon"));
        ...
    }
}

public class HomeController : Controller  
{
    private readonly ICraigMellonGitHubApi _craigMellonGitHubApi ;
    public HomeController(ICraigMellonGitHubApi craigMellonGitHubApi )
    {
        _craigMellonGitHubApi = craigMellonGitHubApi;
    }

    public Task<string> Name() => _craigMellonGitHubApi.GetNameAsync();
}
```

**Comment by onovotny** [comment]
You probably want AddSingleton since there is no state in the service.

**Comment by CraigMellon** [comment]
Awesome, thanks the help, just what I needed
