### ISSUE TITLE
UTF-8 content-type validation in response headers

### ISSUE THREAD

**Issue by allarddenis** [paulcbetts/refit#336]
Hi everyone, 

I am currently facing this exception while attempting to access an Api :

**System.ArgumentException**
`'utf8' is not a supported encoding name. Parameter name: name`

After some research it might come from the header of the response I receive from the api. 
In the response header one can read : 

`Content-Type: application/json; charset=utf8`

It seems to be a problem of validation of response header. The charset parameter does not respect w3org styles as it should be '**charset=utf-8**' or '**charset=UTF-8**' instead of just '**charset=utf8**'. Also, I have no power on changing the Api parameter as it's a third-party one.

The exception seems to be thrown by **ReadAsStringAsync** method that Refit uses to read responses.
https://connect.microsoft.com/VisualStudio/feedback/details/790174/system-net-http-httpcontent-readasstringasync-does-not-handle-imperfect-content-type-headers

One work-around consists in using **ReadAsByteArrayAsync** function instead of **ReadAsStringAsync** to read the response. But it would mean changing Refit code. I don't feel like forking Refit just for that.

For now, I've not managed to find a work-around while using Refit existing code.

Do you guys have any thought/advice/solution on this ? 

Thanks !

**Comment by Cheesebaron** [comment]
ReadAsStringAsync won't be used in the future version of Refit, instead it will use a Stream and use Newtonsoft.Json's JsonReader to parse the contents of the stream. As you noticed yourself, Refit first loads the entire JSON string into memory, then hands it over to Newtonsoft.Json, when it could just stream it instead. This will help a bit on memory overhead in applications fetching a whole bunch of data.

Hopefully Newtonsoft.Json can figure out the encoding that it gets in the Stream just fine.

**Comment by allarddenis** [comment]
Ok, thanks for the answer ! 

Keep going, Refit is a really great :)
