### ISSUE TITLE
CancellationToken not working

### ISSUE THREAD

**Issue by opcodewriter** [paulcbetts/refit#339]
The `CancellationToken` parameter defined in the interface does not seem to be used, when I call `cancellationToken.Cancel()` it's not throwing `TaskCanceledException`.  The call runs until the end like when the method didn't have the parameter, or like it's ignoring it.
To see this I am simulating low network speed.

```
[Headers("Accept: application/json")]
interface IMyApi
{
       [Get("/users/{userId}")]
        Task<string> GetUserAsync(int userId, [Header("U")] string username, [Header("P")] string pass, CancellationToken cancellationToken);
}
```

According to https://github.com/paulcbetts/refit/issues/88, I just need to add a parameter of `CancellationToken` type to my interface.

**UPDATE**: not sure if it matters, I have a Xamarin Android app and the code which calls Refit is in a NETLibrary 1.6. and I am using target fallback:

```
  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
    <PackageTargetFallback>portable-net45+win8+wpa81+wp8</PackageTargetFallback>
  </PropertyGroup>
```

**Comment by Cheesebaron** [comment]
I can't reproduce this. I tested against http://slowwly.robertomurray.co.uk/ and set that to 10 seconds. I cancelled my token after 5 seconds. It threw the TaskCancelledException just fine.

**Comment by opcodewriter** [comment]
@Cheesebaron Thanks. What kind of project is it? (Xamarin, console?)

**Comment by Cheesebaron** [comment]
I tried in a NET Core console app. I can try in a Xamarin app too.

**Comment by michelmoorlag** [comment]
You added the token to the Interface but did you add the actual token in the actual implementation of the method? I think you should be forced by the interface but nevertheless you can check that.

**Comment by opcodewriter** [comment]
@Cheesebaron  See my update in the description at the bottom. Thanks

**Comment by opcodewriter** [comment]
@michelmoorlag I am calling with the token, yes.

**Comment by opcodewriter** [comment]
Meh, I was trying to compile from source code so I could try to debug, but it throws errors I can't figure out how solve

```

1>------ Build started: Project: InterfaceStubGenerator.Core, Configuration: Debug Any CPU ------
1>InterfaceStubGenerator.Core -> D:\Refit-Cloned\refit\InterfaceStubGenerator.Core\bin\Debug\net46\InterfaceStubGenerator.Core.dll
1>InterfaceStubGenerator.cs(50,22,50,32): error CS0012: The type 'MulticastDelegate' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
1>InterfaceStubGenerator.cs(51,31,51,45): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
1>InterfaceStubGenerator.cs(166,71,166,91): error CS0117: 'Assembly' does not contain a definition for 'GetExecutingAssembly'
1>InterfaceStubGenerator.cs(174,61,174,69): error CS1061: 'Type' does not contain a definition for 'Assembly' and no extension method 'Assembly' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
1>Done building project "InterfaceStubGenerator.Core.csproj" -- FAILED.

```

**Comment by Cheesebaron** [comment]
Can't reproduce in a Xamarin Android project either. Just like you I have a "Core" which is NetStandard 1.6 with target fallback so forms can be installed.

Refit is added in both core and droid project.

Then I have two buttons, one for starting a task with a request. The other calling cancel on the CancellationTokenSource. Works fine, a TaskCancelledException is thrown and request seems to be cancelled too.

**Comment by Cheesebaron** [comment]
You can see how I do it here: https://github.com/Cheesebaron/refitcancel works fine.

**Comment by opcodewriter** [comment]
@Cheesebaron  thanks. No idea what the heck is going on. I debugged couple of times my code and I am definitely passing the token parameter.

**Comment by Deilan** [comment]
It's worth to mention that `CancellationToken` is supported in the docs. Along with an example. :)
