### ISSUE TITLE
Building a .NET Standard library using Refit in Docker with .NET Core - mono not found

### ISSUE THREAD

**Issue by slimCODE** [paulcbetts/refit#341]
We have a .NET Standard library using Refit, and would like to integrate CI via GitLab. This means using Docker to build the library, and deploy it to our Nuget server.

We're using the `microsoft/dotnet:1.1-sdk` image, and the `dotnet build` line in our script fails with a `mono: not found` error:
> error MSB3073: The command "mono "/root/.nuget/packages/refit/3.1.0/build/netstandard1.1/../../tools/InterfaceStubGenerator.exe" "obj/Release/netstandard1.5//RefitStubs.g.cs" "/...../...../....." "obj/Release/netstandard1.5/RefitParams.rsp"" exited with code 127.

Does that mean `mono` must always be available to build a project using Refit? It's working on .NET Core, right?

When I compile and deploy this .NET Standard library from my local machine (which has all the .NET tools, including mono), out .NET Core projects work flawlessly.

**Comment by Cheesebaron** [comment]
I think this may have been fixed for the next unreleased versions: https://github.com/paulcbetts/refit/commit/22e4fa46e9036d9d5398728d710e4ad59eb387fb

**Comment by onovotny** [comment]
v 4.0 is out now
