### ISSUE TITLE
Web Scraping?

### ISSUE THREAD

**Issue by wekempf** [paulcbetts/refit#343]
Would you consider adding web scraping support? One possible design idea for this:

Use a WebScrape<T> return type to opt-in. When there the content is assumed to be HTML and it's parsed to create and populate a T instance. T is then a poco that has properties decorated with attributes that indicate how to scrape, similar to [WebGrude](https://github.com/beothorn/webGrude).

I could make an entirely separate library for web scraping, but this project already has a lot of the "client" plumbing you'd want there. If this is something you'd be interested in here, I could even work on it and supply a pull request.

**Comment by bennor** [comment]
It's an interesting idea, but possibly something that's a bit outside the scope of what Refit should do. (Mainly as it will require a number of dependencies that aren't necessary for Refit's main use case.)

Might be better as an extenstion library that leans on Refit to do the heavy lifting?

**Comment by paulcbetts** [comment]
Yep, this should be a separate library!

**Comment by bennor** [comment]
@wekempf This is pretty easy to tack on yourself. Here's an example of using Refit to fake an API for google search (excuse the [HTML parsing with regex](https://stackoverflow.com/a/1732454/14451) -- I was in a hurry when I did this:

```csharp
public interface IGoogleApi
{
	[Get("/search")]
	Task<string> SearchInternal([AliasAs("q")]string query);
}

public static class GoogleApiExtensions
{
	public static async Task<IDictionary<string, Uri>> Search(this IGoogleApi google, string query)
	{
		var result = await google.SearchInternal(query);
		return Regex.Matches(result, @"<h3[^>]*>.*?<a[^>]*href=""/url\?q\=([^&]+)[^>]*>(.*?)</a>.*?</h3>", RegexOptions.Singleline)
			.Cast<Match>()
			.Select(m => m.Groups)
			.GroupBy(m => StringUtils.StripTags(m[2].Value), 
					 m => new Uri(Uri.UnescapeDataString(m[1].Value)))
			.ToDictionary(g => g.Key, g => g.First());
	}
}
```
