### ISSUE TITLE
Build error with refit.targets(29,5).

### ISSUE THREAD

**Issue by TechWatching** [paulcbetts/refit#346]
I have the following error while trying to build my application : 
refit.targets(29,5): error : Object reference not set to an instance of an object. 
The correponding line is the following : <GenerateStubsTask SourceFiles="@(Compile)" BaseDirectory="$(MSBuildProjectDirectory)" OutputFile="$(IntermediateOutputPath)\RefitStubs.g.cs" />

I did not found any issue relative to this particular error.
I am targetting dotnetcore 2.0 on Windows 10 and it's a simple console application that I was just using to test refit.

Could it be a configuration issue with my project ?

**Comment by onovotny** [comment]
Do you have a repro? Can you share your project?

**Comment by TechWatching** [comment]
It was just a simple project  to test refit. I shared my code on https://bitbucket.org/anedelec/testlib/src

**Comment by onovotny** [comment]
I don't know if Paket works. You don't need Paket anymore with the modern Csproj format.

Can you remove that and try adding a `<PackageReference Include="Refit" Version="4.0.0" />` and let me know if that fixes it.

**Comment by TechWatching** [comment]
That was it. It is building correctly using Nuget, but I don't understand why. Packet is supposed to work correctly and retrieve packages from nuget. It brings other features that can be interesting so it's too bad it is not working, I may have configured it badly.
