### ISSUE TITLE
Could not update to package 'Refit 4.0.0'

### ISSUE THREAD

**Issue by KarinBerg** [paulcbetts/refit#348]
Hello,
I tried to update Refit in my portable project from version 3.1.0 to 4.0.0 but I get the following message from the Package Manager.

"Could not install package 'Refit 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

Could you tell me why I can not update anymore? What did you change?

Regards 
Karin

**Comment by onovotny** [comment]
Refit 4.0 only supports .NET Standard 1.4 and higher. You must update your PCL to .NET Standard or keep using the earlier version of Refit. PCL's are legacy and have many issues.

**Comment by KarinBerg** [comment]
OK, thanks. Then I have to stay with Refit 3.1.0 until Akavache supports .NET Standard.

**Comment by Cheesebaron** [comment]
You can install PCLs into .NET Standard libraries with a target fallback. So there is no reason not to migrate.

**Comment by KarinBerg** [comment]
Oh that nice. :) I try this out. Thanks!
Blogentry from James Montemagno about this:
http://motzcod.es/post/148657853472/installing-a-pcl-into-netstandard-libraries
