### ISSUE TITLE
Unable to update from 3.1.0 to 4.0.1

### ISSUE THREAD

**Issue by LuigiMaestrelli** [paulcbetts/refit#350]
`Could not install package 'Refit 4.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
`

I was able to update from 2.4.1 to 3.1.0, but not to 4.0.1.

Any ideas?

**Comment by Cheesebaron** [comment]
You are using a PCL. Refit 4.x is NET Standard 1.4 which is not compatible with PCL

**Comment by LuigiMaestrelli** [comment]
Wow, thank you for the quick response.
