### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by strandloper** [paulcbetts/refit#351]
I have two similar but not identical routes and when I include both in the interface for Refit the call to `RestService.For<IDynamicCanProxy>(url)` is failing with **An item with the same key has already been added**. If I include only one or the other there is no problem.

These are the two interface definitions,

```
[Delete("/canbus/fms/boilerplate/{partialVin}")]
Task<bool> RemoveBoilerplateAsync(string authToken, string partialVin);

[Delete("/canbus/fms/boilerplate/{name}/{version}")]
Task<bool> RemoveBoilerplateAsync(string authToken, string name, string version);
```

The error occurs in RequestBuilderImplementation at

```
interfaceHttpMethods = targetInterface.GetMethods()
                .SelectMany(x => {
                    var attrs = x.GetCustomAttributes(true);
                    var hasHttpMethod = attrs.OfType<HttpMethodAttribute>().Any();
                    if (!hasHttpMethod) return Enumerable.Empty<RestMethodInfo>();

                    return EnumerableEx.Return(new RestMethodInfo(targetInterface, x, settings));
                })
                .ToDictionary(k => k.Name, v => v);
```
I have resolved the issue by renaming one of the methods, which works, indicating that method overloading is breaking due to the method names being used as keys. It may make more sense to base the keys off the entire method signature.

**Comment by onovotny** [comment]
That's correct, overloading doesn't work yet. There's a PR to add these that just needs to be reviewed https://github.com/paulcbetts/refit/pull/349

**Comment by strandloper** [comment]
Great, I will just use differently named methods in the meantime.
