### ISSUE TITLE
Exited with code 127 (MSB3073) with Profile 111

### ISSUE THREAD

**Issue by erossini** [paulcbetts/refit#352]
I have problems when I add your packages v. 3.1.0. I can't find a solution and I can't update it to the new version because my solution needs `Profile 111`. The error is this:

> /Users/enrico/.nuget/packages/refit/3.1.0/build/netstandard1.1/refit.targets(5,5): Error MSB3073: The command "/usr/local/bin/mono "/Users/enrico/.nuget/packages/refit/3.1.0/build/netstandard1.1/../../tools/InterfaceStubGenerator.exe" "obj/Debug/RefitStubs.g.cs" "/Users/enrico/Projects/myproject/MyProject/App/Common" "obj/Debug/RefitParams.rsp"" exited with code 127. (MSB3073)

I don't have a `mono` folder under `/usr/local/bin` but `mono` is only in `/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono`.

<img width="905" alt="screen shot 2017-09-01 at 09 36 46" src="https://user-images.githubusercontent.com/9497415/29963563-3c78fe20-8eff-11e7-8164-c8d7eb0b66f1.png">

**Comment by onovotny** [comment]
Refit 4 uses an MSBuild task so it doesn't need to know the location of Mono.

Closing as we're not releasing any more 3.x versions.
