### ISSUE TITLE
Call to endpoint returning single string returns string with quotes

### ISSUE THREAD

**Issue by strandloper** [paulcbetts/refit#356]
Given the following code
```
using Refit;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

public interface IProxy
{
  [Get("/parameter/system-name/{systemName}")]
  Task<string> GetLatestParameterVersionAsync(string authToken, string systemName);
}

public class Proxy : IProxy
{
  readonly IProxy _proxy;

  public Proxy(string url)
  {
    _proxy = RestService.For<IProxy>(url, new RefitSettings
    {
      JsonSerializerSettings = new JsonSerializerSettings
      {
        Converters = { new StringEnumConverter() }
      }
    });
  }

  public async Task<string> GetLatestParameterVersionAsync(string authToken, string systemName)
  {
    var response = await _proxy.GetLatestParameterVersionAsync(authToken, systemName);
    return response;
  }
}

```
and the following response (as shown by Stackify)
```
Server: Microsoft-IIS/10.0
X-StackifyID: V1|80000018-0000-f900-b63f-84710c7967bb|
Cache-Control: private
X-AspNet-Version: 4.0.30319
Content-Type: application/json; charset=utf-8
Stackify-Length: 9

Response:
"1.0.0.3"
```
the method returns the string including quotations which is unexpected. I have worked around it with `return response.Replace("\"", string.Empty);` but thought it best to raise an issue, in case this is a real problem with deserialization.

**Comment by bennor** [comment]
When your return type is `Task<string>`, we return the raw response body to you, which I am guessing is a JSON encoded string value.

**Comment by strandloper** [comment]
That's right, so this is by design and it's my responsibility to strip the quotes as I'm doing. Will close the issue.

**Comment by bennor** [comment]
Yeah, unfortunately because we provide the full body when the return type is string, we can't automatically deseralize a single JSON encoded string value.
