### ISSUE TITLE
Using from .NET 4.6.1 and .NET Standard 2.0?

### ISSUE THREAD

**Issue by amarwadi** [paulcbetts/refit#358]
Hello, I'm running into issues using this from .NET 4.6.1 and .NET Standard 2.0. It appears that we won't be able to use Refit from Azure functions (which relies on .NET 4.6.1) until the dependency on .NET 4.5 is upgraded to .net 4.6.1. Any chance on doing this anytime soon? Would love to utilize this in a few projects we are working on! Cheerz!

**Comment by onovotny** [comment]
I'm not sure I understand? Functions run on app services and that is on Net 4.7 now.

**Comment by amarwadi** [comment]
Hello, I'm trying to use this from Azure functions and I keep on getting this error: "Exception while executing function: EventSinkFunction. mscorlib: Constructor on type AutoGeneratedIPublicEventsApi' not found.

Any thoughts on this? Sorry I thought this might be happening because of the .NET version

**Comment by amarwadi** [comment]
Hello, Apologies for the confusion. I'm beginning to think that this is an Azure functions issue. I was able to run this from a Console app without any issues.
