### ISSUE TITLE
.Net Core 2 Build

### ISSUE THREAD

**Issue by iamfreee** [paulcbetts/refit#360]
Hi,

Why the need for the .net core 2 sdk to build? Why not the version 1?

Using Rider IDE, .net core 2 is not supported yet.

Thanks

**Comment by onovotny** [comment]
There were a lot of changes in the .NET Core 2 SDK, including support for detecting if the build itself *is* a `dotnet build` or a `msbuild`. You'll need to bother JetBrains about .NET Core 2 I'm afraid.

**Comment by iamfreee** [comment]
Thanks for the answer.
