### ISSUE TITLE
Content-Length no longer set when using Refit 4

### ISSUE THREAD

**Issue by jdluzen** [paulcbetts/refit#362]
I am currently using `3.1.0`, the `Content-Length` header is set on requests. After upgrading to `4.0.1`, it is no longer set.

**Comment by onovotny** [comment]
How are you making the request, what does your API look like? These headers are generally handled by the `HttpContent` derived types and aren't something that Refit ever manually set.

**Comment by jdluzen** [comment]
The test API I used was pretty basic, something like this:
```
[Post("<...>")]
public interface ITemp
{
    Task Test(<some POCO here>);
}
```

I'm not sure, but after searching through the code based on what I know about ASP.NET Streams, their behavior changes when Flush()ing, I suspect this might be it: https://github.com/paulcbetts/refit/commit/879e3d19634152ba7e5c01a2f610d22ebe8af5a8#diff-ef1e95d8d69943f1b3f91e27c7bd5986 With the change, the Length is no longer known.

**Comment by Cheesebaron** [comment]
I guess this is related to `PushStreamContent`, which doesn't calculate the size of the stream prior to uploading. This way you can keep streaming (pushing) chunks of data, I.e. when uploading big blobs, without loading the entire thing into memory.

`PushStreamContent` will return `-1` for `Content-Length`, indicating that data will be pushed:
https://github.com/paulcbetts/refit/commit/879e3d19634152ba7e5c01a2f610d22ebe8af5a8#diff-e9d50c57b943fec07af2cd7e77a33371R154

`StreamContent` is a pull model instead, where the server you are uploading to, knows the content-length header and pulls the data based on that.

This shouldn't change anything on how you receive streamed data server side. In ASP.NET it will be something like:

```
using (var stream = await Request.Content.ReadAsStreamAsync())
{
    // do stuff with the stream...
}
```

**Comment by bennor** [comment]
@Cheesebaron, do you reckon we should maybe make the push stream behaviour something that can be opted out of using a property on the `[Body]` attribute?

**Comment by jdluzen** [comment]
@Cheesebaron agreed that it shouldn't change usage on the server side. Unfortunately, I am using it against a 3rd party API which requires it.

**Comment by Cheesebaron** [comment]
@onovotny @bennor I think an opt-out or opt-in model needs to be implemented. Not sure which one is preferable. Maybe it could be as simple as using `StreamContent` instead of `PushStreamContent` when opting in/out.

**Comment by bennor** [comment]
I think opt-out is preferable. It's not that common for an API to require a content length from the client, is it?

**Comment by Cheesebaron** [comment]
Not that I know off. I don't write my API's like that 😄
