### ISSUE TITLE
Windows store App

### ISSUE THREAD

**Issue by premithk** [paulcbetts/refit#367]
Does Refit support windows store apps (8.1). I remember reading it does in paul's blog (https://log.paulbetts.org/introducing-refit-2-0/), but can't see that in the readme?

**Comment by bennor** [comment]
The older versions supported WinRT (from 2.0 onwards), but I believe it has been removed from 4.0. I would suggest trying the latest 2.*.* build.

**Comment by premithk** [comment]
Oh. Ok, Thank you for the response.
