### ISSUE TITLE
System.NotImplementedException: You've somehow included the PCL version of Refit in your app. You need to use the platform-specific version!

### ISSUE THREAD

**Issue by spurdow** [paulcbetts/refit#373]
Currently using MVVMCross framework referenced the `Core` Project

I have tried this in multiple ways:
-Different versions of refit tested (all the same versions used).
-Tried to setup the DI within the Setup.cs (android platform), instead of the a PCL.
-I even tried to use a shared project instead of a PCL. Only xamarin android had refit installed - no logical way a PCL could break it, but still gave the same error..
-I checked the actual Refit  for Android `\app\packages\refit.2.4.1\lib\MonoAndroid\Refit.dll`
-I checked the actual Refit  for Android `\app\packages\refit.2.4.1\lib\Xamarin.iOS10\Refit.dll`

Have I missed something?

**Comment by onovotny** [comment]
Closing at Refit 2.4.1 is very old. Please try the latest and open a new issue if there's still a problem.
