### ISSUE TITLE
Severity	Code	Description	Project	File	Line	Suppression State Error		Could not install package 'Refit 4.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

### ISSUE THREAD

**Issue by spurdow** [paulcbetts/refit#376]
Currently using Profile 111 .Net Portable 4.5 Installing Refit 4.0.1

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Refit 4.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

```
Posted question on [StackOverflow](https://stackoverflow.com/questions/46470827/severitycodedescriptionprojectfilelinesuppression-state-errorcould-not-in)
Did i miss something?

**Comment by Cheesebaron** [comment]
Yes. 4.x is NET Standard.

**Comment by spurdow** [comment]
I used MvvmCross using PCL as the CORE.

So what should I do?

**Comment by spurdow** [comment]
Can this be used in PCL Core?

**Comment by Cheesebaron** [comment]
Convert your PCL to NET Standard.

**Comment by kalkotekedar** [comment]
I facing the same issue, I have upgraded my PCL to .NET Standard Class Library as shown in the link below

https://xamarinhelp.com/upgrade-pcl-net-standard-class-library/

It works for me.
