### ISSUE TITLE
Support CORS

### ISSUE THREAD

**Issue by thomaseyde** [paulcbetts/refit#383]
CORS is tricky. One of the issues is that `application/json` is not supported.

So it would be nice if Refit:

- Either supported CORS automatically (by checking response headers, I guess).
- Or that we could easily change the mime-type to whatever we want pr request, or for all requests.

**Comment by Cheesebaron** [comment]
`application/json` is supported in preflighted requests. Meaning you need to send an `OPTIONS` request first to figure out if it is safe to send the actual request.

However, simple, not preflighted requests, do not support `application/json` but require the `Content-Type` to be either of:

- `application/x-www-form-urlencoded`
- `multipart/form-data`
- `text/plain`

**Comment by onovotny** [comment]
I'm not really sure what the ask is for this?

CORS is a feature browsers implement to try to prevent scripts from calling API's on other domains. There's nothing stopping any other client from calling that directly in code outside of a browser context.

**Comment by onovotny** [comment]
Closing for now as idle. Please re-open if needed.
