### ISSUE TITLE
Can't reference Refit on Asp.NetCore MVC website

### ISSUE THREAD

**Issue by luccasmf** [paulcbetts/refit#386]
I'm using .Net Core 2.0 but when I install the Refit (last build) via NuGet package it shows me an warning that it's not fully compatible and then I'm not able to reference it on "using" lines

**Comment by Cheesebaron** [comment]
Works fine here when I create a fresh project in Visual Studio 2017, do you have more information?

**Comment by luccasmf** [comment]
Which version of refit did you install?

My project structure:

- .NetCore 2.0 Web Application (MVC)
- Tryed to install Refit 4.0.1

The package is shown on "dependencies" with a flag. But when I try to see it on "NuGet package manager" it doesn't appear like installed

**Comment by luccasmf** [comment]
Creating a new project allows me to add the Refit reference.... -.-
