### ISSUE TITLE
Switching System.Net.Http from Reference to PackageReference?

### ISSUE THREAD

**Issue by BioChristou** [paulcbetts/refit#388]
Would it be possible to change the `System.Net.Http` Reference to a PackageReference when the TargetFramework is 'net45'?

We are investigating an issue in our build system. It appears that when we make NuGet references to Refit and to System.Net.Http in a project, we encounter compile time collisions as the Refit reference to System.Net.Http targets the system-installed dll. We're looking to address our build system's shortcoming, but I thought I'd reach out and ask in the meantime.

**Comment by onovotny** [comment]
We intentionally are referencing the built-in `System.Net.Http` for `net45` to avoid issues with the package...

**Comment by BioChristou** [comment]
What issues are you referring to? I wasn't aware of any problems with the NuGet package for `System.Net.Http`

**Comment by onovotny** [comment]
There were issues with early versions <4.3.1, I believe. The full issue is here: https://github.com/dotnet/corefx/issues/11100 and the postmortem https://github.com/dotnet/corefx/issues/17522
