### ISSUE TITLE
How to pass data with this style

### ISSUE THREAD

**Issue by kore44110** [paulcbetts/refit#390]
I need to pass with this style
[item_name_1, 
item_name_2, 
item_name_3,  ... item_name_n ]

od_dtl_1 : 110
od_dtl_2 : 112
od_dtl_3 : 123
od_dtl_n : value

![capture3](https://user-images.githubusercontent.com/9071822/32614903-db56aede-c5a0-11e7-9884-e69675a54cea.JPG)

can anyone explain sample?
sorry for bad English.

**Comment by Cheesebaron** [comment]
```csharp
[Post("/api")]
Task PostList([Body]List<string> stuff);
```

Where `List<string>` contains your items.

**Comment by kore44110** [comment]
Thanks but it still not working for me

**Comment by Cheesebaron** [comment]
You probably need to be more specific about how you want your data structured.

However, in any case. Bodies are serialized into `json` in Refit. So if your requirement is something json, then Refit will work nicely for you.

**Comment by kore44110** [comment]
Sorry here is my Full data structured Recieve data from my device
![1510137198785](https://user-images.githubusercontent.com/9071822/32618207-9e4a1bbc-c5a9-11e7-9000-9f4e8e7ed8aa.jpg)

in this case, if I sent items = 17 
I need to sent query data od_dtl_1 ... od_dtl_17 [dynamic name query]
but I don't know how to declare the parameter in Task with a dynamic name query

**Comment by bennor** [comment]
You should be able to do it by passing a dictionary:

```csharp
[Post("/api")]
Task PostList([Body] Dictionary<string, object> stuff);
```

**Comment by kore44110** [comment]
Can you explain more sample

**Comment by kore44110** [comment]
Can you explain more sample about Dictionary:
![1](https://user-images.githubusercontent.com/9071822/32697446-1f6864f4-c7c3-11e7-9923-22b91667248f.JPG)
![2](https://user-images.githubusercontent.com/9071822/32697448-25c7c98e-c7c3-11e7-9d0a-8d39ec342e07.JPG)

how possible to make it too flexible with how can I set param by od_dtl_{id}

**Comment by Cheesebaron** [comment]
I think you need to read up on how to use data structures in C#. This is very basic knowledge. 

    data["od_dtl_1"] = 42;

**Comment by kore44110** [comment]
Thank you so much, everyone
