### ISSUE TITLE
Nuget package is out of date

### ISSUE THREAD

**Issue by sahinyyurt** [paulcbetts/refit#397]
Hi,
nuget packages not up to date. it is causing these problems. ex: QueryAttr in  readme but not contain namespace of Refit.
Thank you.

**Comment by bennor** [comment]
Good spotting. We'll aim to get a new version out within the next few days to address this.

**Comment by snickler** [comment]
@sahinyyurt - If you want to use it from the dev branch, clone/download the solution, build and publish in Release. At the locally generated nuget package as a local source and include it in your project.

**Comment by opcodewriter** [comment]
Any plans to release a new version by NuGet? The last one is from mid 2017. Thanks

**Comment by nullsync** [comment]
Please release latest code base to NuGet at least as prerelease. We need to be able to use [Body(buffered: true)]

**Comment by onovotny** [comment]
4.1 is now published online. There's also a CI feed on MyGet here: `https://www.myget.org/F/refit/api/v3/index.json`
