### ISSUE TITLE
Refit requires at least the .NET Core SDK v2.0 to run with 'dotnet build'

### ISSUE THREAD

**Issue by codymullins** [paulcbetts/refit#400]
I'm a little confused by this error - we have installed the core SDK v2.0 on our build server but we still get this error and the build fails. Unless I'm misunderstanding, there's an issue - or there's something else I need to install.

`Refit requires at least the .NET Core SDK v2.0 to run with 'dotnet build'`

Any help is appreciated.

**Comment by Cheesebaron** [comment]
Could you provide some more information? How are you building Refit? With MSBuild or are you running dotnet build?

**Comment by codymullins** [comment]
Sure. We are building the project with dotnet build - `dotnet build -c Release`.

**Comment by Cheesebaron** [comment]
And `dotnet --version` returns 2.0.0 or newer?

Is it the same version used when invoked through your build script? Maybe the PATH is different?

**Comment by codymullins** [comment]
Yes. I even just ran it on my dev machine, still doesn't work.

![image](https://user-images.githubusercontent.com/1738479/34215365-1ebed5ba-e573-11e7-8cb3-a84335416866.png)

**Comment by codymullins** [comment]
Yes. I even just ran it on my dev machine, still doesn't work.

![image](https://user-images.githubusercontent.com/1738479/34215483-72b79990-e573-11e7-8078-df06f07ca45c.png)

**Comment by onovotny** [comment]
Do you have a repro?

**Comment by codymullins** [comment]
@onovotny I just created a blank project (happened to be azure webjob project type) and added the nuget package for Refit, then added a simple interface. Same thing occurs.

https://github.com/codymullins/refitdemoclient

**Comment by onovotny** [comment]
@codymullins if this is your csproj, https://github.com/codymullins/refitdemoclient/blob/master/ClassLibraryDemo/ClassLibraryDemo.csproj, then `dotnet` cannot build that. That's not an "SDK style" project. You have to use `msbuild` for that.

**Comment by codymullins** [comment]
@onovotny we use dotnet build for many of our projects, I just added a blank class library (ClassLibraryDemo2) and `dotnet build` worked fine without Refit added. So I'm not sure I understand?

**Comment by onovotny** [comment]
You may have just gotten lucky then. SDK style projects don't use `packages.config`, and have an `Sdk=` attribute at the top of the csproj bringing in required props/targets files.

you can see this by creating a new .NET Standard class library in VS or using `dotnet new classlib`.
