### ISSUE TITLE
QueryParams are serialized using the current culture

### ISSUE THREAD

**Issue by koen-unifly** [paulcbetts/refit#401]
We had some strange api calls/urls-requests where doubles are represented differently based on the device culture.
For as far as I know there is no standard on how to _serialize_ query parameters.
However this is counter intuitive since Json has a clear format. From my opinion Refit should enforce the same format (use Culture.Invariant), or make it configurable?

**Comment by onovotny** [comment]
@koen-unifly I have a fix for this in the query string, just wanted to confirm you're seeing the correct behavior for JSON serialization or is there something we need to fix there as well?

**Comment by koen-unifly** [comment]
Thanks. We didn't observer the issue with JSON serialization.

**Comment by koen-unifly** [comment]
I am not sure if there is a slack channel, gitter or something else to ask these kind of questions, but:
Is there a nuget package / release planned in the near future?
