### ISSUE TITLE
Seams like SendAsync for DelegateHandlers trigger twice with Refit not if used with just HttpClient as is

### ISSUE THREAD

**Issue by jnormen** [paulcbetts/refit#407]
When I use Refit and add a DelegateHandler to the HttpClient that override SendAsync and then call base.SendAsync it trigger my override method twice 

`var result = await  userService.GetUserAsync("JohnDoe");`

With a DelegateHandler:
```
protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            // See if the request has an authorize header
            var auth = request.Headers.Authorization;
            if (auth != null)
            {
                var token = await _tokenProvider.GetAccessToken().ConfigureAwait(false);
                request.Headers.Authorization = new AuthenticationHeaderValue(auth.Scheme, token);
            }
            
            var result = await base.SendAsync(request, cancellationToken).ConfigureAwait(false);
```

It first calls my override method, then as soon it shall call my base.SendAsync it calls my override Method agin. It gets called twice for just one call. 

```
HttpClient client = new HttpClient(CustomAuthenticatedHttpClientHandler(HttpMessageHandler));
return RestService.For<T>(client);
```

But if I skip using Refit and just use my HttpClient.SendAsync(...) it all works as intended. 
Is this a bug? 

(Using it under .net Standard 2.0)

**Comment by jnormen** [comment]
Seams to be my fault... Created the client with Lazy<T>

**Comment by Cheesebaron** [comment]
Otherwise, if you find it is not your fault. Please provide a small repro sample and we are happy to take a look at the issue.

**Comment by jnormen** [comment]
No it was really my bad... So it was not Lazy either, my test just send in new CustomAuthenticatedHttpClientHandler and in that one accidentally AuthenticatedHttpClientHandler So it was nestled InnerHandlers :/
