### ISSUE TITLE
Proposal: add access to the request context from the ApiException

### ISSUE THREAD

**Issue by KonstantinRyazantsev** [paulcbetts/refit#409]
At the moment, when I catched ```ApiException```, I can retrieve only the request url and the HTTP method. What about headers and body?

The case where I wish to use it, is logging of the request and response, when the server returned an error.

Maybe I missed something, and this can be done another way?

**Comment by onovotny** [comment]
Done, thanks for the suggestion.

**Comment by KonstantinRyazantsev** [comment]
Thanks a lot!
