### ISSUE TITLE
Omitting null values from form urlencoded bodies?

### ISSUE THREAD

**Issue by FieldFlux** [paulcbetts/refit#411]
I'm trying to use an API endpoint that only accepts form url-encoded bodies.

I've defined a request class like so

```
public class SomeRequest
{
   public string SomeField {get; set;}
   public string SomeOtherField {get; set;}
}
```

and an interface:
```
public interface ISomeAPI
{
    [Post("/some/api")]
    Task<SomeResponse> GetSomeResponse([Body(BodySerializationMethod.UrlEncoded)] SomeRequest request);
}
```

If I set SomeField to "someValue" and leave SomeOtherField as null, SomeOtherField gets send anyway:

```SomeField=someValue&SomeOtherField=```

This causes issues with the API that I'm trying to call in that it rejects the response as it is expecting it to either not be sent or contain a non-empty value.

Is there a way to configure Refit to omit null values in a form url-encoded body like there is for JSON via [JsonProperty(NullValueHandling = NullValueHandling.Ignore)] ?

**Comment by onovotny** [comment]
I wonder if there's ever a reason to send empty values for form url-encoded data? Seems like it would be like the query string where null values aren't added to the query string?

Thoughts @bennor @paulcbetts ? Should we strip those by default for form url-encoded?

**Comment by bennor** [comment]
I'm happy to strip them for nulls. If someone needed them there but empty, they could pass an empty string.
