### ISSUE TITLE
Support extension for arbitrary object serialization in query string

### ISSUE THREAD

**Issue by jimmcslim** [paulcbetts/refit#415]
It would be good if Refit supported the ability to serialize arbitrary types to the query string: i.e. other than primitives, strings, `DateTime`, `TimeSpan`, `Uri` as currently listed in `DoNotConvertToQueryMap`. It seems that at the moment Refit does a alphabetic, depth-first search to find the first property that matches one of these criteria.

In my case I tried to express an API using a NodaTime `LocalDate` object. I provided a custom `IUrlParameterFormatter` via `RefitSettings` so that I could set explicitly the format to 'yyyyMMdd' and found that the `parameterValue` parameter wasn't the `LocalDate` object but the value the `IUrlParameterFormatter` observed was that of the property path `LocalDate.Calendar.Id`.

Maybe the simplest solution would be to support `IFormattable` in this list as well - since this should be focused on serializing 'tiny types' not bigger object trees.

I can give this a go and submit a pull request - unless there's a better approach here?

**Comment by onovotny** [comment]
I think supporting `IFormattable` is a good idea that could replace the current fixed primitives list.

For implementation, I'd want to see the format strings inline with the field name, like the way interpolated strings do it.

**Comment by jimmcslim** [comment]
Alternatively, the `QueryAttribute` could be extended to take an optional `Format` property?

    public interface IWebService {
        [Get("/foo/{bar}")]
        public Task GetBar(string bar, [Query(Format="mmYY")]LocalDate date);
    }

Would this be better, given that Refit's approach so far has excluded query string parameters from the url template provided to the method attribute?

**Comment by onovotny** [comment]
Good point...I'd do both. I existing places that are interpolated should be able to support the format strings too.

**Comment by onovotny** [comment]
Implemented in #420

**Comment by skrusty** [comment]
I just ran into this issue, wasn't half glad to see that it was in a release made 10 hours ago ;)
