### ISSUE TITLE
Unexpected Behavior in 4.1 (vs 4.0.1)

### ISSUE THREAD

**Issue by Mike-EEE** [paulcbetts/refit#417]
First off... big fan of this project.  I have been able to use it exactly as prescribed without any problems.  Very much appreciative of the great design here, as well as your support for both Reactive.NET and TPL.

I did just upgrade to 4.1.0, and noticed that my method calls with `decimal` types are not getting passed to the resulting URL.  This results in errors since required parameters are no longer there.  Is there a consideration for 4.1 that I am overlooking?  This of course worked in 4.0.1 flawlessly so no problems there.  I thought I would make sure there's mention of it here.

Thank you for any assistance that you can provide!

**Comment by Cheesebaron** [comment]
This could be related to #402

**Comment by onovotny** [comment]
It's certainly possible though that fix was to ensure that the InvariantCulture was always used for serialization.

What would be helpful in this case is a PR adding a failing unit test that demonstrates the expected (not working) behavior.

**Comment by Mike-EEE** [comment]
Cool. I could possibly help out with that, @onovotny.  However, the API that I am accessing requires authentication, and all of their public-facing calls only accept strings (which work), and not decimals or other types.  If there is a way to easily connect to another service here to provide an example we can use to debug this (that I am assuming can be moved to a locally mocked instance of some sort), I would be willing to help out for the cause. 😄

**Comment by onovotny** [comment]
@Mike-EEE I just added a failing test (see the referenced commit). Will look into it.

**Comment by onovotny** [comment]
Should be fixed in the latest CI builds (as soon as it's finished building). Not totally sure what changed between 4.0.1 and 4.1 given that the code path I was looking at shouldn't have worked in 4.0.1. 🤷‍♂️

**Comment by Mike-EEE** [comment]
Woohoo!  Thank you @onovotny!  That's how it goes sometimes.  I feel your pain. 😆
