### ISSUE TITLE
Unable to send Decimal parameters in querystring

### ISSUE THREAD

**Issue by hugoterelle** [paulcbetts/refit#423]
With the version 4.0.x of the nuget package, I was able to send a request with these parameters:

		[Get("/xxx-api/getsimulation")]
		Task<MyDto> AskSimulation([AliasAs("insz")] string nisNumber,
			[AliasAs("definitiefInkomen")] decimal finalIncome,
			[AliasAs("jaartal")] int year,
			[Header("X-On-Behalf-Of")] string onBehalfOf);

But with the new 4.1.0 nuget version, the decimal parameter ("finalIncome") is not included in the query string.  I need to convert my decimal value to an int32 to be taken in account.

With decimal value:
"/xxx-api/getsimulation?insz=1234567890&jaartal=2015" 

With int32 value:
"/xxx-api/getsimulation?insz=1234567890&definitiefInkomen=40000&jaartal=2015"

**Comment by onovotny** [comment]
This is fixed in the latest CI build if you can use that. We're aiming to get that out in the next week or so.

Closing this as a dup.
