### ISSUE TITLE
'IRequestBuilder' does not contain a definition for 'InterfaceHttpMethods' when building project

### ISSUE THREAD

**Issue by godefroi** [paulcbetts/refit#430]
When building my project, I get the following error:

> 'IRequestBuilder' does not contain a definition for 'InterfaceHttpMethods' and no extension method 'InterfaceHttpMethods' accepting a first argument of type 'IRequestBuilder' could be found (are you missing a using directive or an assembly reference?)

This error occurs in the (automatically generated) file C:\project_path\obj\Release\RefitStubs.g.cs on line 45. Line 45 of that file looks like this:

    methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));

This works in 3.1.0, but does not work in 4.2.0.

**Comment by onovotny** [comment]
Hi,

The format of that file has changed, but it should be auto generated on build. Can you remove your obj directory and try again?

**Comment by godefroi** [comment]
I did, and got an identical error message.

**Comment by onovotny** [comment]
Can you share a build log or a repro? Seems like an old version of the task is generating that file...there's no way the 4.2 version could generate that .g.cs file :)

**Comment by godefroi** [comment]
4.1 works file, just like 3.1.0. If I build the project from the command line (using MSBuild 15.0, from the VS2017 installation), it works fine. If I build from inside Visual Studio, it does not.

It may be relevant that my solution includes another project using Refit 4.0.1. Maybe it's not possible to have two projects using different versions of Refit in the same solution?

**Comment by onovotny** [comment]
I suspect that MSBuild is caching something badly. I would upgrade both to 4.2 and rebuild. It's just luck that 4.0.1 didn't change the format of the generated file.

Good to note that in the docs though.

**Comment by onovotny** [comment]
note that after updating both, you may need to restart VS (and ensure there are no cached vbcscompiler.exe and msbuild.exe processes hanging around if it's really caching something)

**Comment by godefroi** [comment]
Yeah, after updating both to 4.2.0, it works. Probably not your bug, then. Good news, I guess!
