### ISSUE TITLE
Boolean not serializing in Refit 4.3

### ISSUE THREAD

**Issue by KirillVorozhbyanov** [paulcbetts/refit#443]
Hello!
Bool type fields  are not serialized in the query.
This problem appeared in Refit version 4.3. All worked in version 4.2.

_Example_
```
[Get("/myobject")]
Task<List<MyObject>> GetMyObjectsAsync([AliasAs("admin")] bool? admin);
```

**Comment by onovotny** [comment]
Is the value you're passing in null or a true/false?

**Comment by KirillVorozhbyanov** [comment]
I'm passing any value (null, false, true) but In my query this parameter is missing.

**Comment by tcfialho** [comment]
We need that too!
