### ISSUE TITLE
AliasAs does not appear to work on responses

### ISSUE THREAD

**Issue by SeanKilleen** [paulcbetts/refit#450]
Hi all,

Working on a unit test repro for this but while I familiarize myself I figured I'd drop this here.

I've got an API that looks like this (irrelevant pieces omitted)

```csharp
public interface IMyApi
{
    Get("/Organisations?brief=false&skip={skip}&top={top}")]
    Task<List<Organisation>> GetOrganizations(int skip, int top);
}
```

```csharp
public class Organisation
{
    public string ORGANISATION_NAME { get; set; }
}
```

I can retrieve the information accurately using this syntax, but if I want to alias the name using `AliasAs`, I run into trouble.

This works:

```csharp
public class Organisation
{
    [JsonProperty(PropertyName="ORGANISATION_NAME")]
    public string Name { get; set; }
}
```

But this does not:

```csharp
public class Organisation
{
    [AliasAs("ORGANISATION_NAME")]
    public string Name { get; set; }
}
```

When using `AliasAs`, the value is being serialized as null.

As I mentioned, I'll try to see if I can get this working via a test/pr.

**Comment by SeanKilleen** [comment]
OK I've at least proved it out as part of #451. Still diving in but I'll see if I can figure out how to fix it.

**Comment by bennor** [comment]
I'm not sure this is something we need to/want to do. We rely on JSON.NET for converting to/from JSON. 

`[AliasAs]` is our attribute, specifically for query string parameter and form post body property aliasing. JSON.NET doesn't know about it, so you'll have a hard time making it work.

**Comment by SeanKilleen** [comment]
@bennor I see; that's totally valid. It seemed from the `README` that `JsonProperty` and `AliasAs` could be used interchangeably in several scenarios, giving me the impression I should be able to use during response serialization as well. 

I'll change direction on #451 to re-orient it around 1) showing via tests that AliasAs doesn't work and 2) updating the `README` to add clarity where I can.

**Comment by bennor** [comment]
It's potentially something we could call out explicitly in the docs though. 

Maybe it was a mistake adding support for `[JsonProperty]` in form and query string aliasing, as this sort of makes things confusing. The thinking there was that you may already have types with `[JsonProperty]` on them, but I'm not sure that's something that really happens. It should be noted that neither form posts nor query strings are JSON, so supporting that attribute is a bit odd. 

Removing would be a breaking change. Thoughts, @onovotny?

**Comment by bennor** [comment]
@SeanKilleen, yeah thanks. I think clarifying in the docs is a great idea whether we remove support for `[JsonProperty]` in form serialization or not.

**Comment by SeanKilleen** [comment]
@bennor yeah, I don't think it was a mistake to include `JsonProperty`; no need to remove from my perspective. Docs & a unit test should clear things up. PR will be ready soon.
