### ISSUE TITLE
Call Refit Api exposed with version 4.0.1 by a client using version 4.3

### ISSUE THREAD

**Issue by agriffard** [paulcbetts/refit#453]
When I try to instanciate a Refit Api exposed with version 4.0.1 in a client application using version 4.3, this error occurs:

`MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1<System.String> Refit.IRequestBuilder.get_InterfaceHttpMethods()'.`

Here is the following stackTrace, to show that it occurs in a constructor using Unity 5.0 for Dependency Injection :
```
Unity.ObjectBuilder.BuildPlan.DynamicMethod.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context) +61
   Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicMethodBuildPlan.BuildUp(IBuilderContext context) +10
   Unity.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context) +282
   Unity.Builder.BuilderContext.NewBuildUp(Type type, String name, Action`1 childCustomizationBlock) +244
   Unity.ResolverPolicy.NamedTypeDependencyResolverPolicy.Resolve(IBuilderContext context) +25
   lambda_method(Closure , IBuilderContext ) +128
   Unity.ObjectBuilder.BuildPlan.DynamicMethod.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context) +35
   Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicMethodBuildPlan.BuildUp(IBuilderContext context) +10
   Unity.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context) +282
   Unity.UnityContainer.ThrowingBuildUp(IBuilderContext context) +101
```

Can we expect that different versions of Refit between an APi and a client can communicate between each other? 
Or do we have to always stick to the same version between them?

Thank you for your time.

**Comment by agriffard** [comment]
Inspecting the generated dll, I can see the `AutoGenerated...Api` changed between 4.0.1 and 4.3 which is now much simpler but previuosly, it had that kind of line:
`IEnumerable<string> interfaceHttpMethods = requestBuilder.get_InterfaceHttpMethods();`.

**Comment by onovotny** [comment]
That is currently by-design. All of the projects in your solution need to be using the same version of Refit due to changes in the generated code, as you've seen.
