### ISSUE TITLE
Support Web API routing attributes

### ISSUE THREAD

**Issue by JamesNK** [paulcbetts/refit#6]
It would be nice if refit supported Web API attributes (coming in the next version of Web API) so the same routing can be shared on the server and client.

I think the best way to implement this would be to support overriding the underlying model directly (e.g. like IContractResolver in Json.NET) and then having a seperate Refit.WebApi package.

**Comment by onovotny** [comment]
Closing due to age. Please re-open if this is still desired, though I'm not sure how this would work.
