### ISSUE TITLE
Support for CancellationToken's

### ISSUE THREAD

**Issue by onovotny** [paulcbetts/refit#88]
If an interface method that supplies a CancellationToken, Refit should pass it to the underlying HttpClient call

**Comment by mburbea** [comment]
:+1: On this. I currently workaround this by spawning a separate http client for each request, and binding the client's CancelPendingRequest method to the cancellationToken. It's ugly and inefficient, it'd be much nicer to just cancel the request I care about instead of all of them.

**Comment by MKuckert** [comment]
Seems like this feature is implemented, right? I simply add a parameter of type CancellationToken to my method, or am I wrong?

**Comment by onovotny** [comment]
Should be, yes.

**Comment by paulcbetts** [comment]
We did it!

**Comment by michelmoorlag** [comment]
I am a bit lost here. I am using Refit 2.4.1 in a Xamarin Forms project and I would like to be able to cancel requests with a CancellationToken. So If I understand it correct I can add a CancellationToken parameter to the methods in the interface and then pass it in the implementation.
1. Is my assumption correct?
2. Is the location of the parameter important like first, last or?
3. Does version 2.4.1 has this functionality, if not what version does?
4. I am using a customHandler with a overridden  SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) method. Will this cancellationToken be the one that is passed in the implementation?

A small example would be highly appreciated.

**Comment by michelmoorlag** [comment]
I just implemented it and based on that I can conclude the following:
1. Yes
2. Don't know, I have always put the token as first parameter and that seems to work
3. Yes
4. Yes
Maybe somebody who knows more how refit works can confirm this?

**Comment by bennor** [comment]
Yes to all. Doesn't matter what the order of parameters is on your interface (they just get read out as a collection).

**Comment by michelmoorlag** [comment]
Thank you Bennor. 
My app kicks off some requests in the background and in some situation like logout it is really handy to be able to cancel these requests with a cancellationtoken. This now works really well but documentation and samples on this issue are missing while this is quite important feature in my opinion.
If somebody is interested I can share some code how to use it in a CustomHandler.

**Comment by opcodewriter** [comment]
I'm having issues with this, if anybody could check it out I would appreciate some help: https://github.com/paulcbetts/refit/issues/339
