### ISSUE TITLE
More convention: complex type should default to [Body]

### ISSUE THREAD

**Issue by onovotny** [paulcbetts/refit#89]
Right now it seems like you need to put [Body] on a parameter you want to be in the body. How about reversing that or at least making the defaults based on the verb.

I.e., for PUT/POST, a complex type would go in the body and any other parameters to the query string.
for GET, a complex type would translate to a query string parameter along with any other parameters.

**Comment by flagbug** [comment]
Closing this, as it seems to be fixed with #102
