### ISSUE TITLE
Refit causes TFS Builds to fail

### ISSUE THREAD

**Issue by onovotny** [paulcbetts/refit#94]
Issue is that it errors out if the target file (the RefitSubs.cs) is read-only. TFS Team Build (and possibly other build agents) will check files out as read-only. This causes the build to fail.

Suggestion: Generate the file in-memory. Read the target file and only complain if they don't match. In the case of a build server, hopefully a local user already ran the build step and the stubs are up-to-date anyway.

**Comment by pkl728** [comment]
@pierskarsenbarg Did you ever resolve this issue?  I'm having the same issue now.  I can't tell if it's just because TeamCity is in the wrong directory or what when it is trying to do the Pre-build event on my core project.

**Comment by pierskarsenbarg** [comment]
I did what @bennor suggested [here](https://github.com/paulcbetts/refit/issues/97#issuecomment-67710036)

**Comment by CADbloke** [comment]
I just ran into this problem building https://github.com/flagbug/Espera after updating all the Paket packages. Problem was Refit's folder name is `refit`, not `refit.2.2.1` so `Espera\packages\refit\build\refit.targets` is wrong on lines 5 & 9

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <PreBuildEvent>"$(SolutionDir)packages\refit.2.2.1\tools\InterfaceStubGenerator.exe" "$(ProjectDir)RefitStubs.cs" "@(Compile)"</PreBuildEvent>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
    <PreBuildEvent>mono "$(SolutionDir)packages/refit.2.2.1/tools/InterfaceStubGenerator.exe" "$(ProjectDir)RefitStubs.cs" "@(Compile)"</PreBuildEvent>
  </PropertyGroup>
</Project>
```

**Comment by onovotny** [comment]
that sounds like an old version of Refit. The current targets do not have the version in the path or any relation to `$(SolutionDir)`: 
https://github.com/paulcbetts/refit/blob/master/Refit/targets/refit.targets#L26

The current version of Refit is 2.4.1; can you try that?

**Comment by onovotny** [comment]
Closing this issue as the original problem has been solved. Generated files are written to the intermediate output path location (in obj). If there are still issues with TFS Build, then new issues should be opened.
